// Package calls — pion_session.go
//
// openClawSession manages a server-side Pion WebRTC peer connection that acts
// as the "AI physician" end of a voice or video call placed to an OpenClaw
// agent.
//
// Pipeline (per patient turn):
//
//	Patient WebRTC audio (Opus RTP)
//	  → buffer 4 s of packets
//	  → PackOpus → Whisper STT → transcript
//	  → VoiceChat (GPT-4o, physician persona + case context)
//	  → Synthesize (OpenAI TTS, OGG/Opus)
//	  → ParseOggOpus → Pion TrackLocalStaticSample → patient hears AI
//
// For video calls the AI sends audio only (no camera).
package calls

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/pion/webrtc/v3"
	"github.com/pion/webrtc/v3/pkg/media"
)

// ── ICE server configuration ──────────────────────────────────────────────────

var pionICEConfig = webrtc.Configuration{
	ICEServers: []webrtc.ICEServer{
		{URLs: []string{"stun:stun.l.google.com:19302"}},
		{URLs: []string{"stun:stun1.l.google.com:19302"}},
	},
}

// ── openClawSession ───────────────────────────────────────────────────────────

// openClawSession is a live WebRTC session on the server side, acting as the
// AI physician for an OpenClaw call.
type openClawSession struct {
	// Identifiers
	callID      string
	callType    string // "voice" | "video"
	callerID    string // patient's user ID (needed for ICE candidate broadcast)
	agentSlug   string

	// WebRTC
	pc         *webrtc.PeerConnection
	audioTrack *webrtc.TrackLocalStaticSample

	// Signaling back-channel — used to push Pion ICE candidates to the patient.
	hub Broadcaster

	// AI pipeline config
	openAIKey string
	model     string // GPT-4o model name

	// Physician persona (AGENT.md + SOUL.md)
	persona      string
	physicianName string

	// Patient info and case context fetched at session start.
	patientName  string
	caseContext  string

	// Conversation history for the duration of this call.
	histMu  sync.Mutex
	history []voiceTurn

	// Buffered Opus RTP payloads from the patient's audio track.
	bufMu  sync.Mutex
	opusBuf [][]byte // each slice is one RTP payload (one Opus frame)

	// Persistence — used to save the call transcript when the session ends.
	db          *sql.DB
	diagnosisID string
	calleeID    string // physician's user ID

	// Lifecycle
	ctx    context.Context
	cancel context.CancelFunc
}

// ── Constructor ───────────────────────────────────────────────────────────────

// newOpenClawSession loads the physician persona and case context, creates a
// Pion PeerConnection, sets the remote description (patient's SDP offer), and
// returns the session + the SDP answer to send back to the patient.
//
// The caller must call session.Start() after storing it so that ICE candidates
// generated by Pion are forwarded and the audio pipeline is wired up.
func newOpenClawSession(
	parentCtx context.Context,
	hub Broadcaster,
	db *sql.DB,
	openAIKey, model string,
	sess *callSession,
	agentSlug, agentsDir string,
	offerSDP string,
) (*openClawSession, *webrtc.SessionDescription, error) {

	ctx, cancel := context.WithCancel(parentCtx)

	// ── Load physician persona ────────────────────────────────────────────
	persona, err := loadPersonaFiles(agentsDir, agentSlug)
	if err != nil {
		cancel()
		return nil, nil, fmt.Errorf("pion: load persona %s: %w", agentSlug, err)
	}

	physicianName := slugToDisplayName(agentSlug)

	// ── Load case context from DB ─────────────────────────────────────────
	patientName, caseContext, err := loadCaseContext(db, sess.DiagnosisID)
	if err != nil {
		// Non-fatal — continue with empty context.
		log.Printf("pion: load case context for %s: %v", sess.DiagnosisID, err)
	}

	// ── Build Pion PeerConnection ─────────────────────────────────────────
	pc, err := webrtc.NewPeerConnection(pionICEConfig)
	if err != nil {
		cancel()
		return nil, nil, fmt.Errorf("pion: new peer connection: %w", err)
	}

	// ── Create outgoing audio track (AI physician → patient) ──────────────
	audioTrack, err := webrtc.NewTrackLocalStaticSample(
		webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeOpus},
		"audio", "openclaw-"+agentSlug,
	)
	if err != nil {
		pc.Close()
		cancel()
		return nil, nil, fmt.Errorf("pion: create audio track: %w", err)
	}
	if _, err := pc.AddTrack(audioTrack); err != nil {
		pc.Close()
		cancel()
		return nil, nil, fmt.Errorf("pion: add audio track: %w", err)
	}

	s := &openClawSession{
		callID:        sess.CallID,
		callType:      sess.CallType,
		callerID:      sess.CallerID,
		agentSlug:     agentSlug,
		pc:            pc,
		audioTrack:    audioTrack,
		hub:           hub,
		openAIKey:     openAIKey,
		model:         model,
		persona:       persona,
		physicianName: physicianName,
		patientName:   patientName,
		caseContext:   caseContext,
		ctx:           ctx,
		cancel:        cancel,
		db:            db,
		diagnosisID:   sess.DiagnosisID,
		calleeID:      sess.CalleeID,
	}

	// ── WebRTC negotiation ────────────────────────────────────────────────

	// Set remote description — patient's SDP offer.
	offer := webrtc.SessionDescription{
		Type: webrtc.SDPTypeOffer,
		SDP:  offerSDP,
	}
	if err := pc.SetRemoteDescription(offer); err != nil {
		s.Close()
		return nil, nil, fmt.Errorf("pion: set remote description: %w", err)
	}

	// Create answer.
	answer, err := pc.CreateAnswer(nil)
	if err != nil {
		s.Close()
		return nil, nil, fmt.Errorf("pion: create answer: %w", err)
	}
	if err := pc.SetLocalDescription(answer); err != nil {
		s.Close()
		return nil, nil, fmt.Errorf("pion: set local description: %w", err)
	}

	return s, &answer, nil
}

// ── Start — wire callbacks ────────────────────────────────────────────────────

// Start wires up the Pion event callbacks and begins the audio processing
// goroutines.  Call this after the session has been stored so that ICE
// candidates can be forwarded correctly.
func (s *openClawSession) Start() {
	// Trickle ICE — forward each candidate to the patient via the hub.
	s.pc.OnICECandidate(func(c *webrtc.ICECandidate) {
		if c == nil {
			return // gathering complete
		}
		payload, err := candidateToJSON(c)
		if err == nil {
			s.hub.BroadcastToUser(s.callerID, "call.ice-candidate", payload)
		}
	})

	// Log connection-state changes for debugging.
	s.pc.OnConnectionStateChange(func(state webrtc.PeerConnectionState) {
		log.Printf("pion[%s]: connection state → %s", s.callID, state)
		if state == webrtc.PeerConnectionStateFailed ||
			state == webrtc.PeerConnectionStateDisconnected {
			s.Close()
		}
	})

	// When the patient's audio track arrives, start collecting it.
	s.pc.OnTrack(func(track *webrtc.TrackRemote, _ *webrtc.RTPReceiver) {
		if strings.EqualFold(track.Codec().MimeType, webrtc.MimeTypeOpus) {
			go s.collectAudio(track)
		}
	})

	// Start the periodic pipeline trigger.
	go s.pipelineLoop()

	// Greet the patient as soon as the connection is ready.
	go s.sendGreeting()
}

// ── Greeting ─────────────────────────────────────────────────────────────────

func (s *openClawSession) sendGreeting() {
	// Wait briefly for the WebRTC connection to establish.
	select {
	case <-s.ctx.Done():
		return
	case <-time.After(2 * time.Second):
	}

	greeting := fmt.Sprintf("Hello%s, this is Dr. %s. How can I help you today?",
		possessiveName(s.patientName), s.physicianName)

	s.playText(greeting)
}

// ── Audio collector ───────────────────────────────────────────────────────────

// collectAudio reads Opus RTP packets from the patient's track and appends
// their payloads to opusBuf.
func (s *openClawSession) collectAudio(track *webrtc.TrackRemote) {
	for {
		select {
		case <-s.ctx.Done():
			return
		default:
		}

		pkt, _, err := track.ReadRTP()
		if err != nil {
			return
		}

		s.bufMu.Lock()
		s.opusBuf = append(s.opusBuf, pkt.Payload)
		s.bufMu.Unlock()
	}
}

// ── Pipeline loop ─────────────────────────────────────────────────────────────

// pipelineLoop fires every 4 seconds: drains buffered audio, transcribes it,
// generates an AI reply, synthesises speech, and plays it back.
func (s *openClawSession) pipelineLoop() {
	ticker := time.NewTicker(4 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-s.ctx.Done():
			return
		case <-ticker.C:
			s.processTurn()
		}
	}
}

func (s *openClawSession) processTurn() {
	// Drain buffered Opus packets.
	s.bufMu.Lock()
	packets := s.opusBuf
	s.opusBuf = nil
	s.bufMu.Unlock()

	if len(packets) == 0 {
		return // silence — nothing to process
	}

	// ── Whisper STT ──────────────────────────────────────────────────────
	oggData := PackOpus(packets, 1, 48000)
	transcript, err := Transcribe(s.ctx, s.openAIKey, oggData)
	if err != nil {
		log.Printf("pion[%s]: whisper error: %v", s.callID, err)
		return
	}
	transcript = strings.TrimSpace(transcript)
	if transcript == "" {
		return // no speech detected
	}

	log.Printf("pion[%s]: patient said: %q", s.callID, transcript)

	// ── GPT-4o voice chat ─────────────────────────────────────────────────
	s.histMu.Lock()
	histCopy := make([]voiceTurn, len(s.history))
	copy(histCopy, s.history)
	s.histMu.Unlock()

	reply, err := VoiceChat(
		s.ctx,
		s.openAIKey, s.model,
		s.persona, s.physicianName, s.patientName, s.caseContext,
		histCopy, transcript,
	)
	if err != nil {
		log.Printf("pion[%s]: voice_chat error: %v", s.callID, err)
		return
	}
	if reply == "" {
		return
	}

	log.Printf("pion[%s]: AI reply: %q", s.callID, reply)

	// Append to history.
	s.histMu.Lock()
	s.history = append(s.history, voiceTurn{Patient: transcript, Physician: reply})
	s.histMu.Unlock()

	// ── TTS + play ────────────────────────────────────────────────────────
	s.playText(reply)
}

// playText synthesises text to OGG/Opus and writes the frames to the
// outgoing audio track.
func (s *openClawSession) playText(text string) {
	voice := VoiceForSlug(s.agentSlug)
	oggData, err := Synthesize(s.ctx, s.openAIKey, text, voice)
	if err != nil {
		log.Printf("pion[%s]: tts error: %v", s.callID, err)
		return
	}
	if len(oggData) == 0 {
		return
	}

	packets := ParseOggOpus(oggData)
	for _, pkt := range packets {
		select {
		case <-s.ctx.Done():
			return
		default:
		}
		if err := s.audioTrack.WriteSample(media.Sample{
			Data:     pkt,
			Duration: 20 * time.Millisecond,
		}); err != nil {
			log.Printf("pion[%s]: write sample: %v", s.callID, err)
			return
		}
		// Pace the playback at real-time speed.
		time.Sleep(20 * time.Millisecond)
	}
}

// ── AddICECandidate ───────────────────────────────────────────────────────────

// AddICECandidate delivers a patient-side ICE candidate to the Pion PC.
func (s *openClawSession) AddICECandidate(init webrtc.ICECandidateInit) error {
	return s.pc.AddICECandidate(init)
}

// ── SaveTranscript ────────────────────────────────────────────────────────────

// SaveTranscript persists the call conversation history as a single IM message
// (with metadata type "call_transcript") so the patient can review it in the
// Instant Message panel after the call ends.
//
// It is a no-op when the call produced no dialogue.
func (s *openClawSession) SaveTranscript() {
	s.histMu.Lock()
	history := make([]voiceTurn, len(s.history))
	copy(history, s.history)
	s.histMu.Unlock()

	if len(history) == 0 || s.db == nil || s.diagnosisID == "" {
		return
	}

	// ── Build ordered turns slice ─────────────────────────────────────────
	type turn struct {
		Speaker string `json:"speaker"` // "patient" | "physician"
		Text    string `json:"text"`
	}
	turns := make([]turn, 0, len(history)*2)
	for _, h := range history {
		if h.Patient != "" {
			turns = append(turns, turn{Speaker: "patient", Text: h.Patient})
		}
		if h.Physician != "" {
			turns = append(turns, turn{Speaker: "physician", Text: h.Physician})
		}
	}

	// ── Marshal metadata ──────────────────────────────────────────────────
	type transcriptMeta struct {
		Type     string `json:"type"`
		CallType string `json:"call_type"`
		Turns    []turn `json:"turns"`
	}
	meta, err := json.Marshal(transcriptMeta{
		Type:     "call_transcript",
		CallType: s.callType,
		Turns:    turns,
	})
	if err != nil {
		log.Printf("pion[%s]: marshal transcript: %v", s.callID, err)
		return
	}

	// ── Human-readable content (required non-empty by the DB constraint) ──
	label := "Voice"
	if s.callType == "video" {
		label = "Video"
	}
	content := fmt.Sprintf("📞 %s call transcript • %s",
		label,
		time.Now().Format("2 Jan 2006, 15:04"),
	)

	// ── Insert as a 'professional' IM message ─────────────────────────────
	const q = `
		INSERT INTO instant_messages
			(diagnosis_id, sender_id, sender_role, sender_name, content, metadata)
		VALUES ($1, $2, 'professional', $3, $4, $5::jsonb)`

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if _, err := s.db.ExecContext(ctx, q,
		s.diagnosisID, s.calleeID, s.physicianName, content, string(meta),
	); err != nil {
		log.Printf("pion[%s]: save transcript: %v", s.callID, err)
	} else {
		log.Printf("pion[%s]: transcript saved (%d turns)", s.callID, len(turns))
	}
}

// ── Close ─────────────────────────────────────────────────────────────────────

// Close terminates the Pion peer connection and cancels all goroutines.
func (s *openClawSession) Close() {
	s.cancel()
	if s.pc != nil {
		s.pc.Close()
	}
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// loadPersonaFiles reads AGENT.md and SOUL.md from agentsDir/slug/.
func loadPersonaFiles(agentsDir, slug string) (string, error) {
	agentBytes, err := os.ReadFile(filepath.Join(agentsDir, slug, "AGENT.md"))
	if err != nil {
		return "", err
	}
	soulBytes, err := os.ReadFile(filepath.Join(agentsDir, slug, "SOUL.md"))
	if err != nil {
		return "", err
	}
	return string(agentBytes) + "\n\n---\n\n" + string(soulBytes), nil
}

// slugToDisplayName converts "dr-ahmed-musa" → "Ahmed Musa".
func slugToDisplayName(slug string) string {
	parts := strings.Split(slug, "-")
	var out []string
	for _, p := range parts {
		if strings.EqualFold(p, "dr") {
			continue
		}
		if len(p) > 0 {
			out = append(out, strings.ToUpper(p[:1])+p[1:])
		}
	}
	return strings.Join(out, " ")
}

// possessiveName returns ", PatientName" or "" if the name is blank.
func possessiveName(name string) string {
	name = strings.TrimSpace(strings.Split(name, " ")[0]) // first name only
	if name == "" {
		return ""
	}
	return ", " + name
}

// loadCaseContext fetches patient name and a brief case summary from the DB.
func loadCaseContext(db *sql.DB, diagnosisID string) (patientName, context string, err error) {
	const q = `
		SELECT
			u.name,
			d.condition,
			d.urgency,
			COALESCE(d.case_description, ''),
			COALESCE(u.medical_history, ''),
			COALESCE(u.allergies, ''),
			COALESCE(u.current_medications, '')
		FROM diagnoses d
		JOIN users u ON u.id = d.user_id
		WHERE d.id = $1`

	var condition, urgency, caseDesc, medHistory, allergies, meds string
	err = db.QueryRow(q, diagnosisID).Scan(
		&patientName, &condition, &urgency, &caseDesc,
		&medHistory, &allergies, &meds,
	)
	if err != nil {
		return "", "", err
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Condition: %s (urgency: %s)\n", condition, urgency))
	if caseDesc != "" {
		sb.WriteString(fmt.Sprintf("Patient description: %s\n", caseDesc))
	}
	if medHistory != "" && medHistory != "None" {
		sb.WriteString(fmt.Sprintf("Medical history: %s\n", medHistory))
	}
	if allergies != "" && allergies != "None" {
		sb.WriteString(fmt.Sprintf("Known allergies: %s\n", allergies))
	}
	if meds != "" && meds != "None" {
		sb.WriteString(fmt.Sprintf("Current medications: %s\n", meds))
	}

	return patientName, sb.String(), nil
}

// candidateToJSON serialises a Pion ICECandidate to the JSON payload format
// expected by the frontend call.ice-candidate WebSocket event.
func candidateToJSON(c *webrtc.ICECandidate) ([]byte, error) {
	init := c.ToJSON()
	payload := map[string]interface{}{
		"candidate":     init.Candidate,
		"sdpMid":        init.SDPMid,
		"sdpMLineIndex": init.SDPMLineIndex,
	}
	return json.Marshal(payload)
}
