export const COUNTRIES: string[] = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia',
  'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Belarus', 'Belgium', 'Belize',
  'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
  'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
  'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
  'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark',
  'Djibouti', 'Dominican Republic', 'DR Congo', 'Ecuador', 'Egypt', 'El Salvador',
  'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland',
  'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea',
  'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
  'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
  'Kenya', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
  'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
  'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco',
  'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal',
  'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia',
  'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
  'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
  'São Tomé and Príncipe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore',
  'Slovakia', 'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain',
  'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan',
  'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
  'Turkmenistan', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States',
  'Uruguay', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe',
];

export const NIGERIA_STATES: string[] = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
  'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT - Abuja', 'Gombe',
  'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos',
  'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto',
  'Taraba', 'Yobe', 'Zamfara',
];
// Country list and state/province data for registration forms

export const COUNTRY_OPTIONS = [
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'Ghana', value: 'Ghana' },
  { label: 'Kenya', value: 'Kenya' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'United States', value: 'United States' },
  { label: 'Canada', value: 'Canada' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Afghanistan', value: 'Afghanistan' },
  { label: 'Albania', value: 'Albania' },
  { label: 'Algeria', value: 'Algeria' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Azerbaijan', value: 'Azerbaijan' },
  { label: 'Bahrain', value: 'Bahrain' },
  { label: 'Bangladesh', value: 'Bangladesh' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Benin', value: 'Benin' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Botswana', value: 'Botswana' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Burkina Faso', value: 'Burkina Faso' },
  { label: 'Cameroon', value: 'Cameroon' },
  { label: 'Chad', value: 'Chad' },
  { label: 'Chile', value: 'Chile' },
  { label: 'China', value: 'China' },
  { label: "Côte d'Ivoire", value: "Côte d'Ivoire" },
  { label: 'Democratic Republic of Congo', value: 'Democratic Republic of Congo' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Egypt', value: 'Egypt' },
  { label: 'Ethiopia', value: 'Ethiopia' },
  { label: 'Finland', value: 'Finland' },
  { label: 'France', value: 'France' },
  { label: 'Gambia', value: 'Gambia' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Guinea', value: 'Guinea' },
  { label: 'India', value: 'India' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Iran', value: 'Iran' },
  { label: 'Iraq', value: 'Iraq' },
  { label: 'Ireland', value: 'Ireland' },
  { label: 'Israel', value: 'Israel' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Jamaica', value: 'Jamaica' },
  { label: 'Japan', value: 'Japan' },
  { label: 'Jordan', value: 'Jordan' },
  { label: 'Kazakhstan', value: 'Kazakhstan' },
  { label: 'Kuwait', value: 'Kuwait' },
  { label: 'Lebanon', value: 'Lebanon' },
  { label: 'Liberia', value: 'Liberia' },
  { label: 'Libya', value: 'Libya' },
  { label: 'Malaysia', value: 'Malaysia' },
  { label: 'Mali', value: 'Mali' },
  { label: 'Mauritius', value: 'Mauritius' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Morocco', value: 'Morocco' },
  { label: 'Mozambique', value: 'Mozambique' },
  { label: 'Namibia', value: 'Namibia' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'New Zealand', value: 'New Zealand' },
  { label: 'Niger', value: 'Niger' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Oman', value: 'Oman' },
  { label: 'Pakistan', value: 'Pakistan' },
  { label: 'Philippines', value: 'Philippines' },
  { label: 'Poland', value: 'Poland' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Qatar', value: 'Qatar' },
  { label: 'Republic of Congo', value: 'Republic of Congo' },
  { label: 'Romania', value: 'Romania' },
  { label: 'Russia', value: 'Russia' },
  { label: 'Rwanda', value: 'Rwanda' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { label: 'Senegal', value: 'Senegal' },
  { label: 'Sierra Leone', value: 'Sierra Leone' },
  { label: 'Somalia', value: 'Somalia' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Sudan', value: 'Sudan' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Tanzania', value: 'Tanzania' },
  { label: 'Togo', value: 'Togo' },
  { label: 'Tunisia', value: 'Tunisia' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Uganda', value: 'Uganda' },
  { label: 'Ukraine', value: 'Ukraine' },
  { label: 'United Arab Emirates', value: 'United Arab Emirates' },
  { label: 'Venezuela', value: 'Venezuela' },
  { label: 'Vietnam', value: 'Vietnam' },
  { label: 'Yemen', value: 'Yemen' },
  { label: 'Zambia', value: 'Zambia' },
  { label: 'Zimbabwe', value: 'Zimbabwe' },
];

export const COUNTRY_NAMES = COUNTRY_OPTIONS.map((c) => c.value);

/** States by country. Add more mappings as needed. */
export const STATES_BY_COUNTRY: Record<string, string[]> = {
  Nigeria: [
    'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
    'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu',
    'FCT (Abuja)', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina',
    'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo',
    'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
  ],
  Ghana: [
    'Ahafo', 'Ashanti', 'Bono', 'Bono East', 'Central', 'Eastern', 'Greater Accra',
    'North East', 'Northern', 'Oti', 'Savannah', 'Upper East', 'Upper West',
    'Volta', 'Western', 'Western North',
  ],
  Kenya: [
    'Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo-Marakwet', 'Embu', 'Garissa',
    'Homa Bay', 'Isiolo', 'Kajiado', 'Kakamega', 'Kericho', 'Kiambu', 'Kilifi',
    'Kirinyaga', 'Kisii', 'Kisumu', 'Kitui', 'Kwale', 'Laikipia', 'Lamu',
    'Machakos', 'Makueni', 'Mandera', 'Marsabit', 'Meru', 'Migori', 'Mombasa',
    'Murang\'a', 'Nairobi', 'Nakuru', 'Nandi', 'Narok', 'Nyamira', 'Nyandarua',
    'Nyeri', 'Samburu', 'Siaya', 'Taita-Taveta', 'Tana River', 'Tharaka-Nithi',
    'Trans Nzoia', 'Turkana', 'Uasin Gishu', 'Vihiga', 'Wajir', 'West Pokot',
  ],
  'South Africa': [
    'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo',
    'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape',
  ],
  'United Kingdom': [
    'England', 'Scotland', 'Wales', 'Northern Ireland',
  ],
  'United States': [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
    'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
    'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine',
    'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
    'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
    'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
    'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
    'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
    'West Virginia', 'Wisconsin', 'Wyoming', 'District of Columbia',
  ],
  Canada: [
    'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick',
    'Newfoundland and Labrador', 'Northwest Territories', 'Nova Scotia',
    'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon',
  ],
  Australia: [
    'Australian Capital Territory', 'New South Wales', 'Northern Territory',
    'Queensland', 'South Australia', 'Tasmania', 'Victoria', 'Western Australia',
  ],
};

// Phone dial codes — Nigeria first, then all others alphabetically
export const PHONE_CODES: { label: string; value: string }[] = [
  { label: '+234  Nigeria', value: '+234' },
  { label: '+93  Afghanistan', value: '+93' },
  { label: '+355  Albania', value: '+355' },
  { label: '+213  Algeria', value: '+213' },
  { label: '+244  Angola', value: '+244' },
  { label: '+54  Argentina', value: '+54' },
  { label: '+374  Armenia', value: '+374' },
  { label: '+61  Australia', value: '+61' },
  { label: '+43  Austria', value: '+43' },
  { label: '+994  Azerbaijan', value: '+994' },
  { label: '+1242  Bahamas', value: '+1242' },
  { label: '+973  Bahrain', value: '+973' },
  { label: '+880  Bangladesh', value: '+880' },
  { label: '+375  Belarus', value: '+375' },
  { label: '+32  Belgium', value: '+32' },
  { label: '+501  Belize', value: '+501' },
  { label: '+229  Benin', value: '+229' },
  { label: '+975  Bhutan', value: '+975' },
  { label: '+591  Bolivia', value: '+591' },
  { label: '+387  Bosnia and Herzegovina', value: '+387' },
  { label: '+267  Botswana', value: '+267' },
  { label: '+55  Brazil', value: '+55' },
  { label: '+673  Brunei', value: '+673' },
  { label: '+359  Bulgaria', value: '+359' },
  { label: '+226  Burkina Faso', value: '+226' },
  { label: '+257  Burundi', value: '+257' },
  { label: '+855  Cambodia', value: '+855' },
  { label: '+237  Cameroon', value: '+237' },
  { label: '+1  Canada', value: '+1CA' },
  { label: '+238  Cape Verde', value: '+238' },
  { label: '+236  Central African Republic', value: '+236' },
  { label: '+235  Chad', value: '+235' },
  { label: '+56  Chile', value: '+56' },
  { label: '+86  China', value: '+86' },
  { label: '+57  Colombia', value: '+57' },
  { label: '+269  Comoros', value: '+269' },
  { label: '+242  Congo', value: '+242' },
  { label: '+506  Costa Rica', value: '+506' },
  { label: '+225  Côte d\'Ivoire', value: '+225' },
  { label: '+385  Croatia', value: '+385' },
  { label: '+53  Cuba', value: '+53' },
  { label: '+357  Cyprus', value: '+357' },
  { label: '+420  Czech Republic', value: '+420' },
  { label: '+45  Denmark', value: '+45' },
  { label: '+253  Djibouti', value: '+253' },
  { label: '+1809  Dominican Republic', value: '+1809' },
  { label: '+243  DR Congo', value: '+243' },
  { label: '+593  Ecuador', value: '+593' },
  { label: '+20  Egypt', value: '+20' },
  { label: '+503  El Salvador', value: '+503' },
  { label: '+240  Equatorial Guinea', value: '+240' },
  { label: '+291  Eritrea', value: '+291' },
  { label: '+372  Estonia', value: '+372' },
  { label: '+251  Ethiopia', value: '+251' },
  { label: '+679  Fiji', value: '+679' },
  { label: '+358  Finland', value: '+358' },
  { label: '+33  France', value: '+33' },
  { label: '+241  Gabon', value: '+241' },
  { label: '+220  Gambia', value: '+220' },
  { label: '+995  Georgia', value: '+995' },
  { label: '+49  Germany', value: '+49' },
  { label: '+233  Ghana', value: '+233' },
  { label: '+30  Greece', value: '+30' },
  { label: '+502  Guatemala', value: '+502' },
  { label: '+224  Guinea', value: '+224' },
  { label: '+245  Guinea-Bissau', value: '+245' },
  { label: '+592  Guyana', value: '+592' },
  { label: '+509  Haiti', value: '+509' },
  { label: '+504  Honduras', value: '+504' },
  { label: '+36  Hungary', value: '+36' },
  { label: '+354  Iceland', value: '+354' },
  { label: '+91  India', value: '+91' },
  { label: '+62  Indonesia', value: '+62' },
  { label: '+98  Iran', value: '+98' },
  { label: '+964  Iraq', value: '+964' },
  { label: '+353  Ireland', value: '+353' },
  { label: '+972  Israel', value: '+972' },
  { label: '+39  Italy', value: '+39' },
  { label: '+1876  Jamaica', value: '+1876' },
  { label: '+81  Japan', value: '+81' },
  { label: '+962  Jordan', value: '+962' },
  { label: '+7  Kazakhstan', value: '+7KZ' },
  { label: '+254  Kenya', value: '+254' },
  { label: '+965  Kuwait', value: '+965' },
  { label: '+996  Kyrgyzstan', value: '+996' },
  { label: '+856  Laos', value: '+856' },
  { label: '+371  Latvia', value: '+371' },
  { label: '+961  Lebanon', value: '+961' },
  { label: '+266  Lesotho', value: '+266' },
  { label: '+231  Liberia', value: '+231' },
  { label: '+218  Libya', value: '+218' },
  { label: '+370  Lithuania', value: '+370' },
  { label: '+352  Luxembourg', value: '+352' },
  { label: '+261  Madagascar', value: '+261' },
  { label: '+265  Malawi', value: '+265' },
  { label: '+60  Malaysia', value: '+60' },
  { label: '+960  Maldives', value: '+960' },
  { label: '+223  Mali', value: '+223' },
  { label: '+356  Malta', value: '+356' },
  { label: '+222  Mauritania', value: '+222' },
  { label: '+230  Mauritius', value: '+230' },
  { label: '+52  Mexico', value: '+52' },
  { label: '+373  Moldova', value: '+373' },
  { label: '+976  Mongolia', value: '+976' },
  { label: '+382  Montenegro', value: '+382' },
  { label: '+212  Morocco', value: '+212' },
  { label: '+258  Mozambique', value: '+258' },
  { label: '+95  Myanmar', value: '+95' },
  { label: '+264  Namibia', value: '+264' },
  { label: '+977  Nepal', value: '+977' },
  { label: '+31  Netherlands', value: '+31' },
  { label: '+64  New Zealand', value: '+64' },
  { label: '+505  Nicaragua', value: '+505' },
  { label: '+227  Niger', value: '+227' },
  { label: '+850  North Korea', value: '+850' },
  { label: '+389  North Macedonia', value: '+389' },
  { label: '+47  Norway', value: '+47' },
  { label: '+968  Oman', value: '+968' },
  { label: '+92  Pakistan', value: '+92' },
  { label: '+970  Palestine', value: '+970' },
  { label: '+507  Panama', value: '+507' },
  { label: '+675  Papua New Guinea', value: '+675' },
  { label: '+595  Paraguay', value: '+595' },
  { label: '+51  Peru', value: '+51' },
  { label: '+63  Philippines', value: '+63' },
  { label: '+48  Poland', value: '+48' },
  { label: '+351  Portugal', value: '+351' },
  { label: '+974  Qatar', value: '+974' },
  { label: '+40  Romania', value: '+40' },
  { label: '+7  Russia', value: '+7RU' },
  { label: '+250  Rwanda', value: '+250' },
  { label: '+966  Saudi Arabia', value: '+966' },
  { label: '+221  Senegal', value: '+221' },
  { label: '+381  Serbia', value: '+381' },
  { label: '+232  Sierra Leone', value: '+232' },
  { label: '+65  Singapore', value: '+65' },
  { label: '+421  Slovakia', value: '+421' },
  { label: '+386  Slovenia', value: '+386' },
  { label: '+252  Somalia', value: '+252' },
  { label: '+27  South Africa', value: '+27' },
  { label: '+82  South Korea', value: '+82' },
  { label: '+211  South Sudan', value: '+211' },
  { label: '+34  Spain', value: '+34' },
  { label: '+94  Sri Lanka', value: '+94' },
  { label: '+249  Sudan', value: '+249' },
  { label: '+597  Suriname', value: '+597' },
  { label: '+46  Sweden', value: '+46' },
  { label: '+41  Switzerland', value: '+41' },
  { label: '+963  Syria', value: '+963' },
  { label: '+886  Taiwan', value: '+886' },
  { label: '+992  Tajikistan', value: '+992' },
  { label: '+255  Tanzania', value: '+255' },
  { label: '+66  Thailand', value: '+66' },
  { label: '+670  Timor-Leste', value: '+670' },
  { label: '+228  Togo', value: '+228' },
  { label: '+1868  Trinidad and Tobago', value: '+1868' },
  { label: '+216  Tunisia', value: '+216' },
  { label: '+90  Turkey', value: '+90' },
  { label: '+993  Turkmenistan', value: '+993' },
  { label: '+256  Uganda', value: '+256' },
  { label: '+380  Ukraine', value: '+380' },
  { label: '+971  United Arab Emirates', value: '+971' },
  { label: '+44  United Kingdom', value: '+44' },
  { label: '+1  United States', value: '+1US' },
  { label: '+598  Uruguay', value: '+598' },
  { label: '+998  Uzbekistan', value: '+998' },
  { label: '+58  Venezuela', value: '+58' },
  { label: '+84  Vietnam', value: '+84' },
  { label: '+967  Yemen', value: '+967' },
  { label: '+260  Zambia', value: '+260' },
  { label: '+263  Zimbabwe', value: '+263' },
];
