package explore

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

// categoryQuery maps each health category to the YouTube search query used to
// find relevant health education videos.
// Categories are drawn from the full Lifegate platform health domain so that
// the catalogue covers primary care pillars as well as condition-specific areas
// that can be personalised per user on the mobile client.
// aiExclusionSuffix is appended to every YouTube search query to suppress
// AI-generated, text-to-speech, and slideshow videos from results.
const aiExclusionSuffix = " -\"AI generated\" -\"generated by AI\" -\"text to speech\" -\"AI voice\" -slideshow -\"no copyright\""

// aiTitleKeywords are checked (case-insensitive) against a video's title and
// channel name. Any match causes the video to be dropped before it is stored.
var aiTitleKeywords = []string{
	// AI-generated content
	"ai generated",
	"generated by ai",
	"ai narrated",
	"ai voice",
	"ai video",
	"text to speech",
	"tts video",
	"auto generated",
	"robot voice",
	"synthesia",
	"heygen",
	"d-id video",
	"deepfake",
	"ai avatar",
	"ai presenter",
	"elevenlabs",
	"murf ai",
	"voiceover ai",
	"ai doctor",
	"ai physician",
	// Misinformation / conspiracy red flags
	"doctors hate",
	"big pharma doesn",
	"they don't want you to know",
	"cure cancer naturally",
	"cure diabetes naturally",
	"miracle cure",
	"100% cure",
	"doctors won't tell",
	"hidden cure",
	"secret cure",
	"banned cure",
	"government hiding",
	"pharmaceutical conspiracy",
	// Spam / low-quality signals
	"make money",
	"earn money",
	"get rich",
	"free followers",
	"subscriber",
	"#shorts #trending",
	"viral challenge",
	"prank gone wrong",
	"not clickbait",
}

// clickbaitPatterns are regex patterns checked against video titles.
// Videos matching any of these are dropped as low-quality clickbait.
var clickbaitPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)you won'?t believe`),
	regexp.MustCompile(`(?i)doctors? (hate|don'?t want)`),
	regexp.MustCompile(`(?i)this (one )?trick`),
	regexp.MustCompile(`(?i)i (tried|ate|drank).{0,30}(days?|weeks?|months?)\b`),
	regexp.MustCompile(`(?i)\b(insane|unbelievable|shocking|mind.?blowing|jaw.?dropping)\b`),
	regexp.MustCompile(`(?i)\b(gone wrong|gone sexual|gone bad)\b`),
	regexp.MustCompile(`(?i)^\s*[A-Z\s!?]{20,}`),  // all-caps titles (≥20 chars)
	regexp.MustCompile(`[!?]{3,}`),                  // 3+ consecutive ! or ?
}

// trustedChannelKeywords are checked (case-insensitive) against a video's channelTitle
// to identify content from licensed doctors, hospitals, medical schools, and other
// accredited healthcare organisations. The refresher enforces ≥70 % of the final
// video set per category must match at least one of these keywords.
var trustedChannelKeywords = []string{
	// Credentials / titles in the channel name
	"dr.", " dr ", " md", "mbbs", " do ", " rn ", " np ", " pa ",
	// Institution types
	"hospital", "clinic", "medical center", "health center",
	"health system", "medical school", "school of medicine",
	"college of medicine", "faculty of medicine",
	// Well-known organisations
	"mayo", "cleveland clinic", "johns hopkins", "medcram", "webmd",
	"nhs", "cdc", "nih", " who ",
	"american heart", "american diabetes", "american cancer",
	"american college", "american academy",
	// General high-signal terms
	"medical", "medicine", "physician", "surgeon",
	"pharmacy", "pharmacist", "healthcare",
	// Specialty terms in channel name
	"cardiology", "dermatology", "pediatrics", "neurology", "oncology",
	"orthopedic", "psychiatry", "endocrinology", "gastroenterology",
	"gynecology", "urology", "radiology", "pathology",
	"ophthalmology", "rheumatology", "nephrology", "pulmonology",
}

var categoryQuery = map[string]string{
	// ── Platform pillars (always present) ────────────────────────────────
	"Nutrition":     "healthy nutrition diet tips science education doctor",
	"Mental Health": "mental health stress anxiety wellness education therapist",
	"Fitness":       "exercise workout fitness health benefits trainer",
	"Prevention":    "disease prevention health screening checkup physician",
	"Medication":    "medication safety how medicines work pharmacy doctor",
	"Public Health": "public health community disease prevention epidemiology",
	"Primary Care":  "primary care family doctor general practitioner checkup",
	// ── Condition-specific / demographic areas ────────────────────────────
	"Maternal Health":  "maternal health pregnancy antenatal care mother doctor",
	"Cardiology":       "heart health cardiovascular disease blood pressure cardiologist",
	"Diabetes":         "diabetes management blood sugar insulin type 2 diabetes doctor",
	"Chronic Disease":  "chronic disease management long-term condition lifestyle physician",
	"Pediatrics":       "child health pediatric care child development vaccination doctor",
	"Women's Health":   "women health gynecology hormonal health PCOS menstrual doctor",
	"Men's Health":     "men health prostate testosterone sexual health wellness doctor",
	"Sleep & Recovery": "sleep health insomnia sleep disorders recovery rest doctor",
	"Dermatology":      "skin health dermatology eczema acne skincare dermatologist",
}

// categoryMeta carries the display metadata assigned to each category.
var categoryMeta = map[string]struct {
	color string
	icon  string
}{
	// ── Platform pillars ──────────────────────────────────────────────────
	"Nutrition":     {"#f59e0b", "nutrition-outline"},
	"Mental Health": {"#8b5cf6", "happy-outline"},
	"Fitness":       {"#10b981", "barbell-outline"},
	"Prevention":    {"#0284c7", "shield-checkmark-outline"},
	"Medication":    {"#059669", "medkit-outline"},
	"Public Health": {"#0891b2", "earth-outline"},
	"Primary Care":  {"#16a34a", "home-outline"},
	// ── Condition-specific / demographic areas ────────────────────────────
	"Maternal Health":  {"#db2777", "rose-outline"},
	"Cardiology":       {"#ef4444", "heart-outline"},
	"Diabetes":         {"#f97316", "fitness-outline"},
	"Chronic Disease":  {"#dc2626", "pulse-outline"},
	"Pediatrics":       {"#06b6d4", "people-outline"},
	"Women's Health":   {"#ec4899", "female-outline"},
	"Men's Health":     {"#3b82f6", "male-outline"},
	"Sleep & Recovery": {"#6366f1", "moon-outline"},
	"Dermatology":      {"#84cc16", "color-palette-outline"},
}

// ytSearchItem represents a single result from the YouTube search API.
type ytSearchItem struct {
	ID struct {
		VideoID string `json:"videoId"`
	} `json:"id"`
	Snippet struct {
		Title        string `json:"title"`
		Description  string `json:"description"`
		ChannelTitle string `json:"channelTitle"`
		ChannelID    string `json:"channelId"`
	} `json:"snippet"`
}

// minChannelSubscribers is the minimum subscriber count a channel must have for
// its videos to be ingested into the catalogue.
const minChannelSubscribers = 1000

// ytVideoDetails holds contentDetails returned by the videos.list endpoint.
type ytVideoDetails struct {
	ID             string `json:"id"`
	ContentDetails struct {
		Duration string `json:"duration"` // ISO 8601 e.g. PT4M13S
	} `json:"contentDetails"`
}

// Refresher searches YouTube daily and upserts fresh videos into the explore
// catalogue. It keeps the most recent 3 videos per category active and marks
// older entries as inactive.
type Refresher struct {
	repo         *Repository
	apiKey       string
	videosPerCat int
	// lastRunDateByLanguage guards against re-running the same language on the
	// same calendar day. This allows English daily refresh plus on-demand
	// refreshes for a patient's preferred language.
	lastRunDateByLanguage map[string]string
	runMu                 sync.Mutex
}

// NewRefresher creates a Refresher. videosPerCat controls how many fresh
// results to fetch per category on each run (2–4 is recommended to stay
// within the free YouTube Data API quota).
func NewRefresher(repo *Repository, apiKey string, videosPerCat int) *Refresher {
	if videosPerCat < 1 {
		videosPerCat = 3
	}
	return &Refresher{repo: repo, apiKey: apiKey, videosPerCat: videosPerCat, lastRunDateByLanguage: map[string]string{}}
}

// FetchForQueries fetches videos (medium + shorts) from YouTube for a set of
// per-user search queries and upserts them into the shared catalogue. This is
// the on-demand replacement for the old daily cron: videos are pulled only when
// a user needs them, using queries built from that user's profile rather than
// the fixed category taxonomy.
//
// It is safe to call concurrently — the service serialises calls behind its
// refresh mutex. Returns the number of videos upserted and whether the YouTube
// daily quota was hit during the fetch.
func (r *Refresher) FetchForQueries(ctx context.Context, queries []userQuery, language string) (int, bool) {
	if r.apiKey == "" || len(queries) == 0 {
		return 0, false
	}
	language = normalizeExploreLanguage(language)
	sortBase := int(time.Now().Unix())
	total := 0
	quotaHit := false

	for i, uq := range queries {
		select {
		case <-ctx.Done():
			return total, quotaHit
		default:
		}

		// Medium-length videos for this query.
		videos, err := r.searchCategory(ctx, uq.Category, uq.Query, language)
		if err != nil {
			log.Printf("[explore/refresher] on-demand search failed for %q: %v", uq.Query, err)
			if isQuotaError(err) {
				return total, true // quota exhausted — stop, nothing more will succeed
			}
		} else {
			for j, v := range videos {
				if err := r.repo.UpsertVideo(v, sortBase+i*200+j); err != nil {
					log.Printf("[explore/refresher] upsert failed (%s): %v", v.ID, err)
				}
			}
			total += len(videos)
		}

		// Shorts for the same query.
		shorts, err := r.searchCategoryShorts(ctx, uq.Category, uq.Query, language)
		if err != nil {
			if isQuotaError(err) {
				return total, true
			}
		} else {
			for j, v := range shorts {
				if err := r.repo.UpsertVideo(v, sortBase+100000+i*200+j); err != nil {
					log.Printf("[explore/refresher] upsert (short) failed (%s): %v", v.ID, err)
				}
			}
			total += len(shorts)
		}

		// Be polite to the YouTube quota between queries.
		time.Sleep(200 * time.Millisecond)
	}

	log.Printf("[explore/refresher] on-demand fetch: %d video(s) for %d query(ies), lang=%s",
		total, len(queries), language)
	return total, quotaHit
}

// RunOnce executes a single refresh cycle synchronously. It is safe to call
// concurrently — only one execution will run at a time (others return immediately).
// Used by the service layer to populate the catalogue on-demand when the DB is empty.
func (r *Refresher) RunOnce(ctx context.Context) {
	r.RunOnceForLanguage(ctx, defaultExploreLanguage)
}

// RunOnceForLanguage refreshes a specific language catalogue synchronously.
func (r *Refresher) RunOnceForLanguage(ctx context.Context, language string) {
	if r.apiKey == "" {
		return
	}
	r.run(ctx, normalizeExploreLanguage(language))
}

// run performs a single refresh cycle across all categories.
// It is a no-op if it has already run today, preventing quota wastage on
// server restarts or redeploys that can happen multiple times per day.
func (r *Refresher) run(ctx context.Context, language string) {
	language = normalizeExploreLanguage(language)
	today := time.Now().UTC().Format("2006-01-02")

	r.runMu.Lock()
	if r.lastRunDateByLanguage[language] == today {
		r.runMu.Unlock()
		log.Printf("[explore/refresher] Already refreshed today for language=%s — skipping.", language)
		return
	}
	r.lastRunDateByLanguage[language] = today
	r.runMu.Unlock()

	log.Printf("[explore/refresher] Starting YouTube video refresh for language=%s…", language)

	// Build the effective category → query map by merging the static base
	// categories with active trending categories fetched from the DB.
	// This allows trending categories to be rotated by admins without a deploy.
	effectiveCategoryQuery := make(map[string]string, len(categoryQuery))
	for k, v := range categoryQuery {
		effectiveCategoryQuery[k] = v
	}
	if trending, err := r.repo.ListTrendingCategories(); err != nil {
		log.Printf("[explore/refresher] failed to load trending categories: %v — using static set only", err)
	} else {
		for _, tc := range trending {
			effectiveCategoryQuery[tc.Name] = tc.Query
			// Register metadata if not already known (prevents nil-map panics
			// when the refresher constructs Video structs for new categories).
			if _, ok := categoryMeta[tc.Name]; !ok {
				categoryMeta[tc.Name] = struct{ color, icon string }{tc.Color, tc.Icon}
			}
		}
		log.Printf("[explore/refresher] loaded %d trending category(s) from DB", len(trending))
	}

	sortBase := int(time.Now().Unix()) // unique offset per run

	for cat, query := range effectiveCategoryQuery {
		select {
		case <-ctx.Done():
			return
		default:
		}

		videos, err := r.searchCategory(ctx, cat, query, language)
		if err != nil {
			log.Printf("[explore/refresher] search failed for %q: %v", cat, err)
			continue
		}
		if len(videos) == 0 {
			log.Printf("[explore/refresher] no usable results for %q", cat)
			continue
		}

		// Upsert new videos FIRST so there is never a window where a category
		// has zero active rows. DeactivateOldVideos runs after and only marks
		// rows whose updated_at is before today — i.e. the ones we just upserted
		// are safe because their updated_at = NOW().
		for i, v := range videos {
			sortOrder := sortBase + i
			if err := r.repo.UpsertVideo(v, sortOrder); err != nil {
				log.Printf("[explore/refresher] upsert failed for %q (%s): %v", v.Title, v.ID, err)
			}
		}

		// Fetch and upsert Shorts for this category (≤60 s, videoDuration=short).
		shorts, err := r.searchCategoryShorts(ctx, cat, query, language)
		if err != nil {
			log.Printf("[explore/refresher] shorts search failed for %q: %v", cat, err)
		} else {
			for i, v := range shorts {
				sortOrder := sortBase + 1000 + i // offset so shorts sort after medium videos
				if err := r.repo.UpsertVideo(v, sortOrder); err != nil {
					log.Printf("[explore/refresher] upsert (short) failed for %q (%s): %v", v.Title, v.ID, err)
				}
			}
			if len(shorts) > 0 {
				log.Printf("[explore/refresher] refreshed %d short(s) for category %q", len(shorts), cat)
			}
		}

		// Keep a 30-day rolling pool so daily hash-rotation in ListActiveVideos
		// can serve a different subset each day. Only truly stale rows (>30 days
		// without an update) are deactivated.
		cutoff := time.Now().UTC().AddDate(0, 0, -30).Format("2006-01-02")
		if err := r.repo.DeactivateOldVideos(cat, language, cutoff); err != nil {
			log.Printf("[explore/refresher] deactivate failed for %q: %v", cat, err)
		}

		log.Printf("[explore/refresher] refreshed %d video(s) for category %q", len(videos), cat)
		// Be polite to the YouTube API quota — small delay between categories.
		time.Sleep(300 * time.Millisecond)
	}

	log.Println("[explore/refresher] Daily refresh complete.")
}

// searchCategory queries YouTube for videos matching the given category query
// across both medium (4–20 min) and long (>20 min) duration bands, fetches
// exact durations via videos.list, and returns Video objects in the 5–30 min
// range ready for the DB.
func (r *Refresher) searchCategory(ctx context.Context, category, query, language string) ([]Video, error) {
	type searchResp struct {
		Items         []ytSearchItem `json:"items"`
		NextPageToken string         `json:"nextPageToken"`
	}

	// ── 1. Search medium duration band, paging until we collect NEW videos ──
	// YouTube API: medium = 4–20 min. We filter precisely to 5–20 min in code.
	byID := make(map[string]ytSearchItem)

	// Varied publishedAfter each call (7–365 days back) so successive fetches
	// query a different slice of YouTube history and surface different content.
	daysBack := 7 + int(time.Now().UnixNano()/1e6)%358
	publishedAfter := time.Now().UTC().AddDate(0, 0, -daysBack).Format(time.RFC3339)

	// Append exclusion terms to suppress AI-generated content at the API level.
	fullQuery := query + aiExclusionSuffix

	// Target number of NEW (never-fetched) candidate IDs to collect.
	target := r.videosPerCat * 2
	if target > 50 {
		target = 50
	}

	allIDs := make([]string, 0, target) // only IDs that have NEVER been fetched
	pageToken := ""
	const maxPages = 3 // cap quota; each page is one search request

	for page := 0; page < maxPages && len(allIDs) < target; page++ {
		searchURL := fmt.Sprintf(
			"https://www.googleapis.com/youtube/v3/search?part=snippet&q=%s&type=video&videoDuration=medium&maxResults=50&relevanceLanguage=%s&safeSearch=strict&publishedAfter=%s&key=%s",
			url.QueryEscape(fullQuery),
			url.QueryEscape(language),
			url.QueryEscape(publishedAfter),
			r.apiKey,
		)
		if pageToken != "" {
			searchURL += "&pageToken=" + url.QueryEscape(pageToken)
		}

		sr, err := ytGet[searchResp](ctx, searchURL)
		if err != nil {
			if page == 0 {
				return nil, fmt.Errorf("search (medium) request: %w", err)
			}
			break // partial results from earlier pages are still usable
		}

		// Gather this page's candidate IDs (deduped within this fetch).
		pageIDs := make([]string, 0, len(sr.Items))
		for _, it := range sr.Items {
			vid := it.ID.VideoID
			if vid == "" {
				continue
			}
			if _, dup := byID[vid]; dup {
				continue
			}
			byID[vid] = it
			pageIDs = append(pageIDs, vid)
		}

		// Keep only videos that have NEVER been fetched before.
		unseen, ferr := r.repo.FilterUnseenYoutubeIDs(pageIDs)
		if ferr == nil {
			allIDs = append(allIDs, unseen...)
		} else {
			allIDs = append(allIDs, pageIDs...) // dedup unavailable — fall back
		}

		if sr.NextPageToken == "" {
			break
		}
		pageToken = sr.NextPageToken
	}

	if len(allIDs) == 0 {
		return nil, nil
	}
	if len(allIDs) > target {
		allIDs = allIDs[:target]
	}

	// ── 2. Fetch exact durations via videos.list ──────────────────────────
	detailsURL := fmt.Sprintf(
		"https://www.googleapis.com/youtube/v3/videos?part=contentDetails&id=%s&key=%s",
		url.QueryEscape(strings.Join(allIDs, ",")),
		r.apiKey,
	)
	type detailsResp struct {
		Items []ytVideoDetails `json:"items"`
	}
	dr, err := ytGet[detailsResp](ctx, detailsURL)
	if err != nil {
		return nil, fmt.Errorf("details request: %w", err)
	}

	// ── 3. Build Video list — keep only real (non-AI) videos in 3–20 min ──
	meta := categoryMeta[category]
	if meta.color == "" {
		// Unknown category label (per-user condition query) — use brand defaults.
		meta = struct{ color, icon string }{"#0AADA2", "play-circle-outline"}
	}
	var out []Video
	chanByYt := make(map[string]string) // youtubeID → channelID
	for _, d := range dr.Items {
		dur := parseISO8601Duration(d.ContentDetails.Duration)
		// Keep only videos in the 3–20 min range (180–1200 s).
		if dur < 180 || dur > 1200 {
			continue
		}

		snippet := byID[d.ID].Snippet

		// Drop AI-generated, spam, clickbait, or low-quality videos.
		if isLowQualityVideo(snippet.Title, snippet.ChannelTitle, snippet.Description) {
			log.Printf("[explore/refresher] skipping low-quality video: %q (channel: %q)", snippet.Title, snippet.ChannelTitle)
			continue
		}
		desc := snippet.Description
		if len(desc) > 180 {
			desc = desc[:177] + "…"
		}
		desc = strings.ReplaceAll(desc, "\n", " ")

		// Coin tiers: ~5 min = 1 LC, ~10 min = 3 LC, ~15–20 min = 5 LC.
		coins := 1
		if dur >= 900 {
			coins = 5
		} else if dur >= 600 {
			coins = 3
		}

		chanByYt[d.ID] = snippet.ChannelID
		out = append(out, Video{
			ID:              fmt.Sprintf("yt_%s_%s_%s", sanitizeID(language), sanitizeID(category), d.ID),
			Title:           snippet.Title,
			Description:     desc,
			Category:        category,
			Language:        language,
			DurationSeconds: dur,
			Coins:           coins,
			ThumbnailColor:  meta.color,
			ThumbnailIcon:   meta.icon,
			Instructor:      snippet.ChannelTitle,
			YoutubeID:       d.ID,
		})
	}

	// Keep only videos from channels with ≥ minChannelSubscribers subscribers.
	out = r.filterBySubscribers(ctx, out, chanByYt)
	if len(out) == 0 {
		return nil, nil
	}

	// ── Enforce ≥70 % trusted healthcare source target ────────────────────
	// Split into trusted (licensed doctor / accredited institution) and general
	// buckets, then compose: fill trustedQuota slots from trusted first, top up
	// the remainder with general results. Gracefully degrades when there are
	// fewer trusted candidates than the quota (e.g. non-English queries).
	var trusted, general []Video
	for _, v := range out {
		if isTrustedHealthcareChannel(v.Instructor) {
			trusted = append(trusted, v)
		} else {
			general = append(general, v)
		}
	}
	trustedQuota := (r.videosPerCat*8 + 9) / 10 // ⌈80 % of videosPerCat⌉ — raised from 70%
	if len(trusted) > trustedQuota {
		trusted = trusted[:trustedQuota]
	}
	generalQuota := r.videosPerCat - len(trusted)
	if generalQuota < 0 {
		generalQuota = 0
	}
	if len(general) > generalQuota {
		general = general[:generalQuota]
	}
	out = append(trusted, general...)

	achievedPct := 0
	if len(out) > 0 {
		achievedPct = len(trusted) * 100 / len(out)
	}
	log.Printf("[explore/refresher] category %q: %d video(s), %d%% from trusted healthcare sources",
		category, len(out), achievedPct)
	return out, nil
}

// searchCategoryShorts fetches YouTube Shorts (≤60 s) for a category using
// videoDuration=short. Each Short earns 1 LC and is stored with IsShort=true.
// The trusted-source quota is not enforced for Shorts since short-form health
// content is often produced by qualified creators without institution branding.
func (r *Refresher) searchCategoryShorts(ctx context.Context, category, query, language string) ([]Video, error) {
	type searchResp struct {
		Items         []ytSearchItem `json:"items"`
		NextPageToken string         `json:"nextPageToken"`
	}

	// Shorts target = half the number of reel videos per category (rounded up).
	shortsPerCat := (r.videosPerCat + 1) / 2
	if shortsPerCat < 1 {
		shortsPerCat = 1
	}
	fullQuery := query + aiExclusionSuffix
	target := shortsPerCat * 3

	byID := make(map[string]ytSearchItem)
	ids := make([]string, 0, target) // only never-fetched IDs
	pageToken := ""
	const maxPages = 3

	for page := 0; page < maxPages && len(ids) < target; page++ {
		searchURL := fmt.Sprintf(
			"https://www.googleapis.com/youtube/v3/search?part=snippet&q=%s&type=video&videoDuration=short&maxResults=50&relevanceLanguage=%s&safeSearch=strict&key=%s",
			url.QueryEscape(fullQuery),
			url.QueryEscape(language),
			r.apiKey,
		)
		if pageToken != "" {
			searchURL += "&pageToken=" + url.QueryEscape(pageToken)
		}

		sr, err := ytGet[searchResp](ctx, searchURL)
		if err != nil {
			if page == 0 {
				return nil, fmt.Errorf("shorts search request: %w", err)
			}
			break
		}

		pageIDs := make([]string, 0, len(sr.Items))
		for _, it := range sr.Items {
			vid := it.ID.VideoID
			if vid == "" {
				continue
			}
			if _, dup := byID[vid]; dup {
				continue
			}
			byID[vid] = it
			pageIDs = append(pageIDs, vid)
		}

		// Keep only Shorts that have never been fetched before.
		unseen, ferr := r.repo.FilterUnseenYoutubeIDs(pageIDs)
		if ferr == nil {
			ids = append(ids, unseen...)
		} else {
			ids = append(ids, pageIDs...)
		}

		if sr.NextPageToken == "" {
			break
		}
		pageToken = sr.NextPageToken
	}

	if len(ids) == 0 {
		return nil, nil
	}
	if len(ids) > target {
		ids = ids[:target]
	}

	detailsURL := fmt.Sprintf(
		"https://www.googleapis.com/youtube/v3/videos?part=contentDetails&id=%s&key=%s",
		url.QueryEscape(strings.Join(ids, ",")),
		r.apiKey,
	)
	type detailsResp struct {
		Items []ytVideoDetails `json:"items"`
	}
	dr, err := ytGet[detailsResp](ctx, detailsURL)
	if err != nil {
		return nil, fmt.Errorf("shorts details request: %w", err)
	}

	meta := categoryMeta[category]
	if meta.color == "" {
		meta = struct{ color, icon string }{"#0AADA2", "play-circle-outline"}
	}
	var out []Video
	chanByYt := make(map[string]string) // youtubeID → channelID
	for _, d := range dr.Items {
		dur := parseISO8601Duration(d.ContentDetails.Duration)
		// Keep only genuine Shorts (≤60 s).
		if dur <= 0 || dur > 60 {
			continue
		}

		snippet := byID[d.ID].Snippet
		if isLowQualityVideo(snippet.Title, snippet.ChannelTitle, snippet.Description) {
			continue
		}

		desc := snippet.Description
		if len(desc) > 180 {
			desc = desc[:177] + "…"
		}
		desc = strings.ReplaceAll(desc, "\n", " ")

		chanByYt[d.ID] = snippet.ChannelID
		out = append(out, Video{
			ID:              fmt.Sprintf("yt_short_%s_%s_%s", sanitizeID(language), sanitizeID(category), d.ID),
			Title:           snippet.Title,
			Description:     desc,
			Category:        category,
			Language:        language,
			DurationSeconds: dur,
			Coins:           1, // Shorts always earn 1 LC
			ThumbnailColor:  meta.color,
			ThumbnailIcon:   meta.icon,
			Instructor:      snippet.ChannelTitle,
			YoutubeID:       d.ID,
			IsShort:         true,
		})
	}

	// Keep only Shorts from channels with ≥ minChannelSubscribers, then cap to
	// the per-category target (half the reels count).
	out = r.filterBySubscribers(ctx, out, chanByYt)
	if len(out) > shortsPerCat {
		out = out[:shortsPerCat]
	}
	return out, nil
}

// isQuotaError reports whether a YouTube API error is a daily-quota exhaustion.
func isQuotaError(err error) bool {
	if err == nil {
		return false
	}
	s := err.Error()
	return strings.Contains(s, "quotaExceeded") ||
		strings.Contains(s, "dailyLimitExceeded") ||
		strings.Contains(s, "HTTP 403")
}

// fetchChannelSubscribers returns channelID → subscriber count for the given
// channels (batched 50 per channels.list call). Channels that hide their
// subscriber count are omitted, so callers treat them as below threshold.
func (r *Refresher) fetchChannelSubscribers(ctx context.Context, channelIDs []string) (map[string]int64, error) {
	result := make(map[string]int64, len(channelIDs))
	if len(channelIDs) == 0 {
		return result, nil
	}
	type channelsResp struct {
		Items []struct {
			ID         string `json:"id"`
			Statistics struct {
				SubscriberCount       string `json:"subscriberCount"`
				HiddenSubscriberCount bool   `json:"hiddenSubscriberCount"`
			} `json:"statistics"`
		} `json:"items"`
	}

	for i := 0; i < len(channelIDs); i += 50 {
		end := i + 50
		if end > len(channelIDs) {
			end = len(channelIDs)
		}
		batch := channelIDs[i:end]
		u := fmt.Sprintf(
			"https://www.googleapis.com/youtube/v3/channels?part=statistics&id=%s&key=%s",
			url.QueryEscape(strings.Join(batch, ",")),
			r.apiKey,
		)
		resp, err := ytGet[channelsResp](ctx, u)
		if err != nil {
			return result, err // propagate so quota errors surface
		}
		for _, it := range resp.Items {
			if it.Statistics.HiddenSubscriberCount {
				continue // unknown count — treat as below threshold
			}
			n, _ := strconv.ParseInt(it.Statistics.SubscriberCount, 10, 64)
			result[it.ID] = n
		}
	}
	return result, nil
}

// filterBySubscribers keeps only videos whose channel has at least
// minChannelSubscribers. chanByYt maps a video's YouTube ID to its channel ID.
func (r *Refresher) filterBySubscribers(ctx context.Context, vids []Video, chanByYt map[string]string) []Video {
	if len(vids) == 0 {
		return vids
	}
	// Collect unique channel IDs referenced by these videos.
	seen := make(map[string]struct{})
	chanIDs := make([]string, 0, len(vids))
	for _, v := range vids {
		ch := chanByYt[v.YoutubeID]
		if ch == "" {
			continue
		}
		if _, dup := seen[ch]; dup {
			continue
		}
		seen[ch] = struct{}{}
		chanIDs = append(chanIDs, ch)
	}

	subs, err := r.fetchChannelSubscribers(ctx, chanIDs)
	if err != nil {
		// On a stats lookup failure (e.g. quota) don't silently keep everything —
		// but also don't drop everything: skip the filter so we still return
		// content, and let the quota flag surface via the search calls.
		log.Printf("[explore/refresher] subscriber lookup failed: %v — skipping subscriber filter", err)
		return vids
	}

	kept := vids[:0]
	for _, v := range vids {
		if subs[chanByYt[v.YoutubeID]] >= minChannelSubscribers {
			kept = append(kept, v)
		}
	}
	return kept
}

// ytGet performs a GET request to the YouTube API and unmarshals the response
// into T. It is a package-level generic function (methods cannot be generic in Go).
func ytGet[T any](ctx context.Context, rawURL string) (T, error) {
	var zero T
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return zero, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return zero, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return zero, err
	}
	if resp.StatusCode != http.StatusOK {
		return zero, fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(body))
	}

	var result T
	if err := json.Unmarshal(body, &result); err != nil {
		return zero, err
	}
	return result, nil
}

// parseISO8601Duration converts a YouTube duration string (PT4M13S) to seconds.
func parseISO8601Duration(s string) int {
	s = strings.TrimPrefix(s, "PT")
	var total, cur int
	for _, c := range s {
		switch {
		case c >= '0' && c <= '9':
			cur = cur*10 + int(c-'0')
		case c == 'H':
			total += cur * 3600
			cur = 0
		case c == 'M':
			total += cur * 60
			cur = 0
		case c == 'S':
			total += cur
			cur = 0
		}
	}
	return total
}

// isTrustedHealthcareChannel returns true when the channel name contains at least
// one keyword indicating a licensed doctor, accredited hospital, medical school,
// or official health organisation. Used to enforce the ≥80 % trusted-source target.
func isTrustedHealthcareChannel(channelTitle string) bool {
	lower := strings.ToLower(channelTitle)
	for _, kw := range trustedChannelKeywords {
		if strings.Contains(lower, kw) {
			return true
		}
	}
	return false
}

// isLowQualityVideo returns true when a video should be rejected for spam,
// clickbait, misinformation, or insufficient description quality.
// Called for both medium-length videos and Shorts.
func isLowQualityVideo(title, channelTitle, description string) bool {
	titleLower   := strings.ToLower(title)
	channelLower := strings.ToLower(channelTitle)
	descLower    := strings.ToLower(description)

	// AI-generated / spam keyword match
	for _, kw := range aiTitleKeywords {
		if strings.Contains(titleLower, kw) ||
			strings.Contains(channelLower, kw) ||
			strings.Contains(descLower, kw) {
			return true
		}
	}

	// Clickbait pattern match on title
	for _, pat := range clickbaitPatterns {
		if pat.MatchString(title) {
			return true
		}
	}

	// Description quality gate — very short descriptions indicate low-effort content
	if len(strings.TrimSpace(description)) < 30 {
		return true
	}

	return false
}

// sanitizeID converts a category name to a lowercase underscore identifier.
func sanitizeID(cat string) string {
	return strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(cat, " ", "_"), "/", "_"))
}
