package explore

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"
)

// categoryQuery maps each health category to the YouTube search query used to
// find relevant health education videos.
// Categories are drawn from the full Lifegate platform health domain so that
// the catalogue covers primary care pillars as well as condition-specific areas
// that can be personalised per user on the mobile client.
// aiExclusionSuffix is appended to every YouTube search query to suppress
// AI-generated, text-to-speech, and slideshow videos from results.
const aiExclusionSuffix = " -\"AI generated\" -\"generated by AI\" -\"text to speech\" -\"AI voice\" -slideshow -\"no copyright\""

// aiTitleKeywords are checked (case-insensitive) against a video's title and
// channel name. Any match causes the video to be dropped before it is stored.
var aiTitleKeywords = []string{
	"ai generated",
	"generated by ai",
	"ai narrated",
	"ai voice",
	"ai video",
	"text to speech",
	"tts video",
	"auto generated",
	"robot voice",
	"synthesia",
	"heygen",
	"d-id video",
	"deepfake",
	"ai avatar",
	"ai presenter",
}

var categoryQuery = map[string]string{
	// ── Platform pillars (always present) ────────────────────────────────
	"Nutrition":     "healthy nutrition diet tips science education doctor",
	"Mental Health": "mental health stress anxiety wellness education therapist",
	"Fitness":       "exercise workout fitness health benefits trainer",
	"Prevention":    "disease prevention health screening checkup physician",
	"Medication":    "medication safety how medicines work pharmacy doctor",
	"Public Health": "public health community disease prevention epidemiology",
	"Primary Care":  "primary care family doctor general practitioner checkup",
	// ── Condition-specific / demographic areas ────────────────────────────
	"Maternal Health":  "maternal health pregnancy antenatal care mother doctor",
	"Cardiology":       "heart health cardiovascular disease blood pressure cardiologist",
	"Diabetes":         "diabetes management blood sugar insulin type 2 diabetes doctor",
	"Chronic Disease":  "chronic disease management long-term condition lifestyle physician",
	"Pediatrics":       "child health pediatric care child development vaccination doctor",
	"Women's Health":   "women health gynecology hormonal health PCOS menstrual doctor",
	"Men's Health":     "men health prostate testosterone sexual health wellness doctor",
	"Sleep & Recovery": "sleep health insomnia sleep disorders recovery rest doctor",
	"Dermatology":      "skin health dermatology eczema acne skincare dermatologist",
}

// categoryMeta carries the display metadata assigned to each category.
var categoryMeta = map[string]struct {
	color string
	icon  string
}{
	// ── Platform pillars ──────────────────────────────────────────────────
	"Nutrition":     {"#f59e0b", "nutrition-outline"},
	"Mental Health": {"#8b5cf6", "happy-outline"},
	"Fitness":       {"#10b981", "barbell-outline"},
	"Prevention":    {"#0284c7", "shield-checkmark-outline"},
	"Medication":    {"#059669", "medkit-outline"},
	"Public Health": {"#0891b2", "earth-outline"},
	"Primary Care":  {"#16a34a", "home-outline"},
	// ── Condition-specific / demographic areas ────────────────────────────
	"Maternal Health":  {"#db2777", "rose-outline"},
	"Cardiology":       {"#ef4444", "heart-outline"},
	"Diabetes":         {"#f97316", "fitness-outline"},
	"Chronic Disease":  {"#dc2626", "pulse-outline"},
	"Pediatrics":       {"#06b6d4", "people-outline"},
	"Women's Health":   {"#ec4899", "female-outline"},
	"Men's Health":     {"#3b82f6", "male-outline"},
	"Sleep & Recovery": {"#6366f1", "moon-outline"},
	"Dermatology":      {"#84cc16", "color-palette-outline"},
}

// ytSearchItem represents a single result from the YouTube search API.
type ytSearchItem struct {
	ID struct {
		VideoID string `json:"videoId"`
	} `json:"id"`
	Snippet struct {
		Title        string `json:"title"`
		Description  string `json:"description"`
		ChannelTitle string `json:"channelTitle"`
	} `json:"snippet"`
}

// ytVideoDetails holds contentDetails returned by the videos.list endpoint.
type ytVideoDetails struct {
	ID             string `json:"id"`
	ContentDetails struct {
		Duration string `json:"duration"` // ISO 8601 e.g. PT4M13S
	} `json:"contentDetails"`
}

// Refresher searches YouTube daily and upserts fresh videos into the explore
// catalogue. It keeps the most recent 3 videos per category active and marks
// older entries as inactive.
type Refresher struct {
	repo         *Repository
	apiKey       string
	videosPerCat int
	// lastRunDateByLanguage guards against re-running the same language on the
	// same calendar day. This allows English daily refresh plus on-demand
	// refreshes for a patient's preferred language.
	lastRunDateByLanguage map[string]string
	runMu                 sync.Mutex
}

// NewRefresher creates a Refresher. videosPerCat controls how many fresh
// results to fetch per category on each run (2–4 is recommended to stay
// within the free YouTube Data API quota).
func NewRefresher(repo *Repository, apiKey string, videosPerCat int) *Refresher {
	if videosPerCat < 1 {
		videosPerCat = 3
	}
	return &Refresher{repo: repo, apiKey: apiKey, videosPerCat: videosPerCat, lastRunDateByLanguage: map[string]string{}}
}

// Start runs the daily refresh loop. It fires once immediately at startup (to
// populate fresh content on first deploy) and then again at every subsequent
// midnight UTC so that fresh videos are available at the start of each new
// calendar day regardless of when the server was started.
func (r *Refresher) Start(ctx context.Context) {
	if r.apiKey == "" {
		log.Println("[explore/refresher] YOUTUBE_DATA_API_KEY not set — skipping daily refresh")
		return
	}

	// Run immediately on startup.
	r.run(ctx, defaultExploreLanguage)

	for {
		// Sleep until the next midnight UTC.
		now := time.Now().UTC()
		nextMidnight := time.Date(now.Year(), now.Month(), now.Day()+1, 0, 0, 0, 0, time.UTC)
		select {
		case <-time.After(time.Until(nextMidnight)):
			r.run(ctx, defaultExploreLanguage)
		case <-ctx.Done():
			return
		}
	}
}

// RunOnce executes a single refresh cycle synchronously. It is safe to call
// concurrently — only one execution will run at a time (others return immediately).
// Used by the service layer to populate the catalogue on-demand when the DB is empty.
func (r *Refresher) RunOnce(ctx context.Context) {
	r.RunOnceForLanguage(ctx, defaultExploreLanguage)
}

// RunOnceForLanguage refreshes a specific language catalogue synchronously.
func (r *Refresher) RunOnceForLanguage(ctx context.Context, language string) {
	if r.apiKey == "" {
		return
	}
	r.run(ctx, normalizeExploreLanguage(language))
}

// run performs a single refresh cycle across all categories.
// It is a no-op if it has already run today, preventing quota wastage on
// server restarts or redeploys that can happen multiple times per day.
func (r *Refresher) run(ctx context.Context, language string) {
	language = normalizeExploreLanguage(language)
	today := time.Now().UTC().Format("2006-01-02")

	r.runMu.Lock()
	if r.lastRunDateByLanguage[language] == today {
		r.runMu.Unlock()
		log.Printf("[explore/refresher] Already refreshed today for language=%s — skipping.", language)
		return
	}
	r.lastRunDateByLanguage[language] = today
	r.runMu.Unlock()

	log.Printf("[explore/refresher] Starting YouTube video refresh for language=%s…", language)

	sortBase := int(time.Now().Unix()) // unique offset per run

	for cat, query := range categoryQuery {
		select {
		case <-ctx.Done():
			return
		default:
		}

		videos, err := r.searchCategory(ctx, cat, query, language)
		if err != nil {
			log.Printf("[explore/refresher] search failed for %q: %v", cat, err)
			continue
		}
		if len(videos) == 0 {
			log.Printf("[explore/refresher] no usable results for %q", cat)
			continue
		}

		// Upsert new videos FIRST so there is never a window where a category
		// has zero active rows. DeactivateOldVideos runs after and only marks
		// rows whose updated_at is before today — i.e. the ones we just upserted
		// are safe because their updated_at = NOW().
		for i, v := range videos {
			sortOrder := sortBase + i
			if err := r.repo.UpsertVideo(v, sortOrder); err != nil {
				log.Printf("[explore/refresher] upsert failed for %q (%s): %v", v.Title, v.ID, err)
			}
		}

		// Keep a 30-day rolling pool so daily hash-rotation in ListActiveVideos
		// can serve a different subset each day. Only truly stale rows (>30 days
		// without an update) are deactivated.
		cutoff := time.Now().UTC().AddDate(0, 0, -30).Format("2006-01-02")
		if err := r.repo.DeactivateOldVideos(cat, language, cutoff); err != nil {
			log.Printf("[explore/refresher] deactivate failed for %q: %v", cat, err)
		}

		log.Printf("[explore/refresher] refreshed %d video(s) for category %q", len(videos), cat)
		// Be polite to the YouTube API quota — small delay between categories.
		time.Sleep(300 * time.Millisecond)
	}

	log.Println("[explore/refresher] Daily refresh complete.")
}

// searchCategory queries YouTube for videos matching the given category query
// across both medium (4–20 min) and long (>20 min) duration bands, fetches
// exact durations via videos.list, and returns Video objects in the 5–30 min
// range ready for the DB.
func (r *Refresher) searchCategory(ctx context.Context, category, query, language string) ([]Video, error) {
	type searchResp struct {
		Items []ytSearchItem `json:"items"`
	}

	// ── 1. Search medium duration band (4–20 min) ──────────────────────────
	// YouTube API: medium = 4–20 min. We filter precisely to 5–20 min in code.
	allIDs := make([]string, 0, r.videosPerCat)
	byID := make(map[string]ytSearchItem, r.videosPerCat)

	// Rotate publishedAfter through 12 bi-weekly windows over ~6 months so
	// each run queries a different slice of YouTube's content history and
	// gradually diversifies the pool. Window index cycles 0-11 by week-of-year.
	weekOfYear := time.Now().UTC().YearDay() / 7 // 0–52
	windowIndex := weekOfYear % 12               // 0–11
	// Older window = older content, newer window = recent uploads.
	// Range: 14–180 days back in 14-day steps across 12 windows.
	daysBack := 14 + windowIndex*14
	publishedAfter := time.Now().UTC().AddDate(0, 0, -daysBack).Format(time.RFC3339)

	// Append exclusion terms to suppress AI-generated content at the API level.
	fullQuery := query + aiExclusionSuffix

	searchURL := fmt.Sprintf(
		"https://www.googleapis.com/youtube/v3/search?part=snippet&q=%s&type=video&videoDuration=medium&maxResults=%d&relevanceLanguage=en&safeSearch=strict&publishedAfter=%s&key=%s",
		url.QueryEscape(fullQuery),
		r.videosPerCat,
		url.QueryEscape(publishedAfter),
		r.apiKey,
	)
	searchURL = strings.Replace(searchURL, "relevanceLanguage=en", "relevanceLanguage="+url.QueryEscape(language), 1)
	sr, err := ytGet[searchResp](ctx, searchURL)
	if err != nil {
		return nil, fmt.Errorf("search (medium) request: %w", err)
	}
	for _, it := range sr.Items {
		vid := it.ID.VideoID
		if _, seen := byID[vid]; !seen {
			allIDs = append(allIDs, vid)
			byID[vid] = it
		}
	}

	if len(allIDs) == 0 {
		return nil, nil
	}

	// ── 2. Fetch exact durations via videos.list ──────────────────────────
	detailsURL := fmt.Sprintf(
		"https://www.googleapis.com/youtube/v3/videos?part=contentDetails&id=%s&key=%s",
		url.QueryEscape(strings.Join(allIDs, ",")),
		r.apiKey,
	)
	type detailsResp struct {
		Items []ytVideoDetails `json:"items"`
	}
	dr, err := ytGet[detailsResp](ctx, detailsURL)
	if err != nil {
		return nil, fmt.Errorf("details request: %w", err)
	}

	// ── 3. Build Video list — keep only real (non-AI) videos in 3–20 min ──
	meta := categoryMeta[category]
	var out []Video
	for _, d := range dr.Items {
		dur := parseISO8601Duration(d.ContentDetails.Duration)
		// Keep only videos in the 3–20 min range (180–1200 s).
		if dur < 180 || dur > 1200 {
			continue
		}

		snippet := byID[d.ID].Snippet

		// Drop AI-generated videos: check title and channel against keyword list.
		titleLower := strings.ToLower(snippet.Title)
		channelLower := strings.ToLower(snippet.ChannelTitle)
		descLower := strings.ToLower(snippet.Description)
		aiDetected := false
		for _, kw := range aiTitleKeywords {
			if strings.Contains(titleLower, kw) ||
				strings.Contains(channelLower, kw) ||
				strings.Contains(descLower, kw) {
				aiDetected = true
				break
			}
		}
		if aiDetected {
			log.Printf("[explore/refresher] skipping AI-generated video: %q (channel: %q)", snippet.Title, snippet.ChannelTitle)
			continue
		}
		desc := snippet.Description
		if len(desc) > 180 {
			desc = desc[:177] + "…"
		}
		desc = strings.ReplaceAll(desc, "\n", " ")

		// Coin tiers: ~5 min = 1 LC, ~10 min = 3 LC, ~15–20 min = 5 LC.
		coins := 1
		if dur >= 900 {
			coins = 5
		} else if dur >= 600 {
			coins = 3
		}

		out = append(out, Video{
			ID:              fmt.Sprintf("yt_%s_%s_%s", sanitizeID(language), sanitizeID(category), d.ID),
			Title:           snippet.Title,
			Description:     desc,
			Category:        category,
			Language:        language,
			DurationSeconds: dur,
			Coins:           coins,
			ThumbnailColor:  meta.color,
			ThumbnailIcon:   meta.icon,
			Instructor:      snippet.ChannelTitle,
			YoutubeID:       d.ID,
		})
	}
	return out, nil
}

// ytGet performs a GET request to the YouTube API and unmarshals the response
// into T. It is a package-level generic function (methods cannot be generic in Go).
func ytGet[T any](ctx context.Context, rawURL string) (T, error) {
	var zero T
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return zero, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return zero, err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return zero, err
	}
	if resp.StatusCode != http.StatusOK {
		return zero, fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(body))
	}

	var result T
	if err := json.Unmarshal(body, &result); err != nil {
		return zero, err
	}
	return result, nil
}

// parseISO8601Duration converts a YouTube duration string (PT4M13S) to seconds.
func parseISO8601Duration(s string) int {
	s = strings.TrimPrefix(s, "PT")
	var total, cur int
	for _, c := range s {
		switch {
		case c >= '0' && c <= '9':
			cur = cur*10 + int(c-'0')
		case c == 'H':
			total += cur * 3600
			cur = 0
		case c == 'M':
			total += cur * 60
			cur = 0
		case c == 'S':
			total += cur
			cur = 0
		}
	}
	return total
}

// sanitizeID converts a category name to a lowercase underscore identifier.
func sanitizeID(cat string) string {
	return strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(cat, " ", "_"), "/", "_"))
}
