-- 023_remove_seed_videos.sql
-- Remove all hand-curated seed videos from the explore catalogue.
-- The YouTube Data API refresher (internal/explore/refresher.go) sources
-- and maintains the live catalogue automatically; no static seeds are needed.
-- explore_video_rewards rows cascade-delete via the FK on video_id.

DELETE FROM explore_videos
WHERE id IN (
  -- 020 original seeds
  'vid_blood_pressure',
  'vid_mediterranean_diet',
  'vid_exercise_brain',
  'vid_stress_anxiety',
  'vid_vaccines',
  'vid_gut_health',
  'vid_sleep_hygiene',
  'vid_medication_labels',
  'vid_diabetes_prevention',
  'vid_mindfulness',
  'vid_hydration',
  'vid_walking_benefits',
  -- 021 YouTube-sourced seeds
  'vid_nutrition_life',
  'vid_balanced_diet',
  'vid_food_brain',
  'vid_eating_tips',
  'vid_stress_adolescents',
  'vid_daily_stress_habits',
  'vid_mindfulness_practice',
  'vid_start_exercising',
  'vid_exercise_benefits',
  'vid_cardio_vs_strength',
  'vid_prevention_levels',
  'vid_checkup_myths',
  'vid_annual_checkup',
  'vid_medication_safety',
  'vid_medication_admin',
  'vid_prenatal_care',
  'vid_antenatal_what',
  'vid_postpartum_depression',
  'vid_what_is_public_health',
  'vid_infectious_disease_control',
  'vid_communicable_diseases',
  'vid_primary_care_importance',
  'vid_first_primary_visit',
  'vid_primary_care_questions',
  -- 022 extended seeds
  'vid_digestive_system',
  'vid_obesity_science',
  'vid_gut_brain_axis',
  'vid_fiber_importance',
  'vid_protein_sources',
  'vid_micronutrients',
  'vid_depression_explained',
  'vid_anxiety_brain',
  'vid_grief_loss',
  'vid_emotional_regulation',
  'vid_self_compassion',
  'vid_therapy_works',
  'vid_burnout_recovery',
  'vid_sedentary_danger',
  'vid_how_muscles_grow',
  'vid_vo2max',
  'vid_hiit_science',
  'vid_flexibility_matters',
  'vid_active_recovery',
  'vid_posture_health',
  'vid_blood_pressure_basics',
  'vid_cancer_prevention',
  'vid_heart_disease_prev',
  'vid_handwashing_science',
  'vid_skin_cancer_basics',
  'vid_sleep_prevention',
  'vid_antibiotics_how',
  'vid_painkillers_science',
  'vid_generic_vs_brand',
  'vid_drug_interactions',
  'vid_vaccine_types',
  'vid_adherence_matters',
  'vid_otc_safety',
  'vid_antimicrobial_res',
  'vid_fetal_development',
  'vid_breastfeeding_science',
  'vid_gestational_diabetes',
  'vid_preeclampsia',
  'vid_exercise_pregnancy',
  'vid_newborn_first_days',
  'vid_maternal_nutrition',
  'vid_epidemics_spread',
  'vid_herd_immunity',
  'vid_social_determinants',
  'vid_clean_water_health',
  'vid_ncds_global',
  'vid_mental_health_stigma',
  'vid_climate_health',
  'vid_when_see_doctor',
  'vid_talk_to_doctor',
  'vid_blood_tests_explained',
  'vid_chronic_condition_mgmt',
  'vid_telehealth_guide',
  'vid_preventive_screening',
  'vid_doctor_patient_relationship'
);
