-- Seed additional Span v1 patient records from the July 2026 bulk registration list.
-- Rows without a usable email address are ignored. Duplicate emails are inserted once.
-- When age band or gender were not supplied in the source list, dob/gender are left NULL.

WITH raw_records(name, age_band, email, gender) AS (
  VALUES
    ('Wilfred agubamah', '18-24', 'Wilfredagubamah@gmail.com', 'Male'),
    ('Abdulrasheed khadijat akorede', '18-24', 'khayhay015@gmail.com', 'Female'),
    ('Afolabi Matthew', '18-24', 'labimatthew@gmail.com', 'Male'),
    ('Hammed suleiman Adonoyi', '25-34', 'Hammedas789@gmail.com', 'Male'),
    ('Umosen nize ine', '18-24', 'Umosenime325@gmail.com', 'Female'),
    ('Joy Peter', '18-24', 'Peterjoy101425@gmail.com', 'Female'),
    ('Anas Haruna', '25-34', 'engineertakai@gmail.com', 'Male'),
    ('Mohammad Hauwau Dawood', '18-24', 'hauwamdawood@gmail.com', 'Female'),
    ('Salma rabiuabdulkadir', '18-24', 'Salmarabiuabdulkadiir@gmail.com', 'Female'),
    ('Fatima bukar', '18-24', 'Fatimabukar251@gmail.com', 'Female'),
    ('TAHIRU BESHIRU', '25-34', 'beshirutahiru998@gmail.com', 'Male'),
    ('Khalisa usman', '18-24', 'khalisausman01@gmail.com', 'Female'),
    ('Eseyin Abayomi Emmanuel', '25-34', 'emmanuelabayomi2121@gmail.com', 'Male'),
    ('Samson Bitrus visa', '35-44', 'samsonbitrusvisa@gmail.com', 'Male'),
    ('Idakoriko Bilikis Ize', '18-24', 'izebilikis@gmail.com', 'Female'),
    ('Yunusa Ramotu', '18-24', 'yunusaramotu547@gmail.com', 'Female'),
    ('Igah Favour Ada', '18-24', 'favourigah2020@gmail.com', 'Female'),
    ('Oyewumi Victor Olanrewaju', '18-24', 'victorlanrewaju01@gmail.com', 'Male'),
    ('Abdullahi Abubakar', '25-34', 'abdullahiabubakar352@gmail.com', 'Male'),
    ('Adam Balogun Opeyemi', '25-34', 'ope4balo@gmail.com', 'Male'),
    ('Mustapha Muhammed Alilu', '18-24', 'Mustaphamusty177@gmail.com', 'Male'),
    ('Shuaibu Fatima Imam', '18-24', 'shuaibufatimaimam@gmail.com', 'Female'),
    ('Abdulazeez Hamza', '18-24', 'hamzaadeizaa@gmail.com', 'Male'),
    ('Overview Chinyere', '18-24', 'Chinyereokereke018@gmail.com', 'Female'),
    ('Aliyu umar faruk', '18-24', 'Faruqaliyu865@gmail.com', 'Male'),
    ('Olowosulu Elizabeth irewole', '18-24', 'elizabetholowosulu@gmail.com', 'Female'),
    ('Kehinde bukola', '18-24', 'Suzzanbukola3@gmail.com', 'Female'),
    ('Mathias Amed', '35-44', 'dinisoft.dev@gmail.com', 'Male'),
    ('Doris Dalyop', '18-24', 'dorisdalyop@gmail.com', 'Female'),
    ('Umogbai Sonia', '18-24', 'umogbaisonia@gmail.com', 'Female'),
    ('Gaiya Catherine', '25-34', 'gaiyacheryl@gmail.com', 'Female'),
    ('David Genevieve sim', '18-24', 'davidgenevieve67@gmail.com', 'Female'),
    ('Ezekiel Diana', '18-24', 'ezekieldiana08@gmail.com', 'Female'),
    ('David Ogoh Okoh', '18-24', 'Okohdave908@gmail.com', 'Male'),
    ('Ojochebo ogbadu', '18-24', 'Only.chebo@gmail.com', 'Male'),
    ('Favour Abel', '18-24', 'favourabel466@gmail.com', 'Female'),
    ('Laah keziah', '18-24', 'Keziahlaah77@gmail.com', 'Female'),
    ('SIMON DOGO SHESHI', '25-34', 'simondogosheshi@gmail.com', 'Male'),
    ('Ibrahim Mallam Aliyu', '25-34', 'mallam4ibrahim@gmail.com', 'Male'),
    ('Inuwa Mohammed usman', '18-24', 'Usmanmuhammadinuwa219@gmail.com', 'Male'),
    ('Gift Anayo', '18-24', 'Onyeinyechianayo@gmail.com', 'Female'),
    ('Suleiman Amina', '25-34', 'Suleimanamina214@gmail.com', 'Female'),
    ('Faiza Yusuf', '18-24', 'Faizacoyusuf@gmail.com', 'Female'),
    ('Abbas Maryam', '25-34', 'mabbas0605@gmail.com', 'Female'),
    ('ABUBAKAR TAHIRAH ASABE', '18-24', 'tahiraabubakar2@gmail.com', 'Female'),
    ('Ishaya Martins kamai', '25-34', 'ishaya041@gmail.com', 'Male'),
    ('Olajumoke Odetayo', '25-34', 'christexx01@gmail.com', 'Female'),
    ('Yahaya Fatimatulbatool Oyizami', 'Under 18', 'yahayafatimat232@gmail.com', 'Female'),
    ('John Attah', '35-44', 'jsattah06@gmail.com', 'Male'),
    ('Clara osikha', '18-24', 'emmcla2@gmail.com', 'Female'),
    ('Abdulrazak Khadijat', NULL, 'kkhadijat225@gmail.com', NULL),
    ('Imran Iliyas', NULL, 'imranailiyasu63@gmail.com', NULL),
    ('Abah Veronica', NULL, 'vabah699@gmail.com', NULL),
    ('maduba Danladi', NULL, 'maduba45@gmail.com', NULL),
    ('haruna abubakar', NULL, 'harunaabubakarmazari@gmail.com', NULL),
    ('Bello Awwal', NULL, 'belloawwal00@gmail.com', NULL),
    ('hauwa shuaiba', NULL, 'hshuaibu38@gmail.com', NULL),
    ('abdullahi muhammad falalu', NULL, 'falaluabdullahimuhammad0@gmail.com', NULL),
    ('lilian iwuji', NULL, 'lilianaloysuis@gmail.com', NULL),
    ('abdullahi rukkaiy garba', NULL, 'abdullahirukaiyagarba62@gmail.com', NULL),
    ('garuba moshood ajadi', NULL, 'moshooodajadi2@gmail.com', NULL),
    ('hafsat muktar kaigama', NULL, 'hafsatmuktarkaigama@gmail.com', NULL),
    ('Maryam Sani', NULL, 'maryamsani9682@gmail.com', NULL),
    ('Susan Micheal', NULL, 'susannamicheal8@gmail.com', NULL),
    ('Moses Manasseh', NULL, 'ochoyodam2@gmail.com', NULL),
    ('Zion Olumide', NULL, 'zionolumide1@gmail.com', NULL),
    ('Hafsat Ahmad Kalmalo', NULL, 'hafsatahmadkalmalo@gmail.com', NULL),
    ('Ibrahim Zulaihat', NULL, 'izulaihat536@gmail.com', NULL),
    ('Manasseh Benedict', NULL, 'manassehbenedict37@gmail.com', NULL),
    ('Precious Olatunde', NULL, 'preciousolahmicheals@gmail.com', NULL),
    ('Iornongu Msughter', NULL, 'solomoniornongu25@gmail.com', NULL),
    ('Gloria David', NULL, 'glodavid150@gmail.com', NULL),
    ('Abdulfatai Yakubu', NULL, 'yakubuabdulfatai32@gmail.com', NULL),
    ('Danjuma Gloria', NULL, 'gloriadanjuma123@gmail.com', NULL),
    ('Monica Haruna', NULL, 'moniharu25@gmail.com', NULL),
    ('Muhsina Aliyu', NULL, 'muhsinaaliyu2@gmail.com', NULL),
    ('Musa Ibrahim', NULL, 'mibamalli68@gmail.com', NULL),
    ('Firdausi Nuraddeen Ismail', NULL, 'firdausinuraddeenismail@gmail.com', NULL),
    ('Musa Dalhatu Khairr', NULL, 'mdalhat@gmail.com', NULL),
    ('Muhammad Lawal Dikko', NULL, 'dikkolawal60@gmail.com', NULL),
    ('Jamiu Olatunde', NULL, 'kamaldeenmuhammed3@gmail.com', NULL),
    ('Favour Hanna Ibrahim', NULL, 'ibrahimfavour274@gmail.com', NULL),
    ('Herbert Treasure', NULL, 'godselectherbert@gmail.com', NULL),
    ('Jibril Tanimu Musa', NULL, 'jibriltanimumusa@gmail.com', NULL),
    ('Shamsudeen Ahmed', NULL, 'Shamsudeenahmed08@gmail.com', NULL),
    ('Idongesit ilIniouong', NULL, 'effionjidongesit635@gmail.com', NULL),
    ('Emanuel Lena Naomi', NULL, 'lenaemmanuel00@gmail.com', NULL),
    ('Stephanie Ogundiran', NULL, 'Stephanieogundiran75@gmail.com', NULL),
    ('Aliyu Haruna', NULL, 'ibrahimaliyuhydar@gmail.com', NULL),
    ('Akanbi Sodiq', NULL, 'akanbisodiq13@gmail.com', NULL),
    ('Magdaline Yohanna', NULL, 'magdalineyohanna088@gmail.com', NULL),
    ('Maryam Abubakar', NULL, 'maryamabubakar.00642@gmail.com', NULL),
    ('Haziary Ibrahim akanbi', NULL, 'haziaryi@gmail.com', NULL),
    ('Abdulmalik Abubakar Alkali', NULL, 'abdulmalikalkaliabubakar@gmail.com', NULL),
    ('Favour Sim Sati', NULL, 'satifavour59@gmail.com', NULL),
    ('Best luck', NULL, 'bestluckakpabio4@gmail.com', NULL),
    ('Aminu Ishaq', NULL, 'aminshaq01@gmail.com', NULL),
    ('Ahmed Zubair', NULL, 'zubairahmad2861@gmail.com', NULL),

    ('Sulyman halimat adu', '25-34', 'abodunrinhaleemart30@gmail.com', 'Female'),
    ('Adewale Sukurat Adedoyim', '18-24', 'sukuratadewale68@gmail.com', 'Female'),
    ('Ahmad, Shehu Musa', '45-54', 'abbanfauzy@gmail.com', 'Male'),
    ('Edoh Anthonia', '18-24', 'anthoniaedoh23@gmail.com', 'Female'),
    ('Eleche Evelyn', '18-24', 'elechepurity@gmail.com', 'Female'),
    ('Songu Terngu Emmanuel', '18-24', 'songuemmanuel186@gmail.com', 'Male'),
    ('Adoji Hannah usman', '18-24', 'adojihannah@gmail.com', 'Female'),
    ('Mustapha Favour Dogo', '18-24', 'favourmustapha436@gmail.com', 'Female'),
    ('Vincent Abiodun Akinlade', '25-34', 'akinzoluwatobi@gmail.com', 'Male'),
    ('Adelakun Maryam Adeteju', '18-24', 'adegokeadeteju001@gmail.com', 'Female'),
    ('John Attah', '45-54', 'jsattah06@gmail.com', 'Male'),
    ('Chukwu Prudence Chikodi', '25-34', 'prudencecharles70@gmail.com', 'Female'),
    ('Abdulmalik Khadija Yusuf', '18-24', 'khadijahabdulmalik176@gmail.com', 'Female'),
    ('Isma''ila Umaru Ojo', '45-54', 'umoruojo@gmail.com', 'Male'),
    ('Adejoh Mary Helen', '18-24', 'Adejohmary2000@gmail.com', 'Female'),
    ('Maryam Hassan Pariyae', '18-24', 'hassmaryampariya493@gmail.com', 'Female'),
    ('SHEHU-ABDULRAZAQ ABDULQOYUM OLADIPUPO', '18-24', 'shehuabdulqoyum@gmail.com', 'Male'),
    ('Fatima Aliyu ismail', '18-24', 'Aleeuzayyad9@gmail.com', 'Female'),
    ('Alpheu oluwatoyin Deborah', '18-24', 'isrealalpheu@gmail.com', 'Female'),
    ('Ishaq Zara Jibril', '25-34', 'zaraishaqjibril@gmail.com', 'Female'),
    ('Nasir ummulkhairi muhammad', '18-24', 'nasirummulkhairim1114@gmail.com', 'Female'),
    ('Abdulmalik Fatima Yusuf', 'Under 18', 'Zarahsco@gmail.com', 'Female'),
    ('Lapinni fatimah', '18-24', 'LapinniF@gmail.com', 'Female'),
    ('Fatima zara''u Aliyu', 'Under 18', 'fatimaaliyu1460@gmail.com', 'Female'),
    ('Hassan Zahra shehu', '18-24', 'zahrashehuhassan@gmail.com', 'Female'),
    ('Sunday Odubu', '55-64', 'scodubu893@gmail.com', 'Male'),
    ('Mustapha khadijah', '18-24', 'Khadijahmustapha9089@gmail.com', 'Female'),
    ('Yusuf Abdulkarim', '18-24', 'abdulkarimyusuf2007@gmail.com', 'Male'),
    ('Zainab Sani Jibril', '18-24', 'zainabsanijibril77@gmail.com', 'Female'),
    ('Onikoyi raheemat', '18-24', 'Raheemajubril@gmail.com', 'Female'),
    ('Rahila bala Muhammad', '18-24', 'Rahilabalamuhammad@gmail.com', 'Female'),
    ('Abdulhakeem salamat', '18-24', 'Abdulhakeemsalmah4@gmail.com', 'Female'),
    ('Abdulhamid Faruk', '35-44', 'abdulhamidfaruk37@gmail.com', 'Male'),
    ('NANA AISHA ISHAQ', '18-24', 'nanaaishaishaq56@gmail.com', 'Female'),
    ('Musa Ganiyah Oleshin', '18-24', 'Oleshingoniyah@gmail.com', 'Female'),
    ('Idara valentine', '25-34', 'Valentineidara@gmail.com', 'Female'),
    ('Fatima Oyiza Danladi', '18-24', 'fatimadanladi495@gmail.com', 'Female'),
    ('Taheebat Abdulauf', NULL, 'Tahibatmahmud@gmail.com', 'Female'),
    ('Salako Precious', '18-24', 'precioussalako33@gmail.com', 'Female'),
    ('Khadijah Muhammad', '18-24', 'Khadeejahmahmmad@gmail.com', 'Female'),
    ('Rashidat oyiza Ismail', '18-24', 'rashidatismail15@gmail.com', 'Female'),
    ('Bitrus kalibu Namadi', '18-24', 'bitruskalibu@gmail.com', 'Male'),
    ('Muhsinah Abdulsalam', '18-24', 'muhsinahabdulsalam386@gmail.com', 'Female'),
    ('Abdulmumin Hajara', '18-24', 'hajaraabdul226@gmail.com', 'Female'),
    ('Abdulsalam abdulrahman', '18-24', 'abdulsalamabdulrahman943@gmail.com', 'Male'),
    ('Muhammed Oyiza Zainab', '18-24', 'oyiza258@gmail.com', 'Female'),
    ('Yusuf Abdulkadir', '25-34', 'yabdulkadir480@gmail.com', 'Male'),
    ('Mohammed Hussain', 'Under 18', 'hussainmohammednabhan@gmail.com', 'Male'),
    ('Salim Mustapha Jatau', '18-24', 'salimmustaphajatau@gmail.com', 'Male'),
    ('Shuaibu saidu maidawa', '18-24', 'Abbahmaidawa@gmail.com', 'Male'),
    ('Muhammad Fatima Mustapha', '18-24', 'fatimamu186@gmail.com', 'Female'),
    ('Tajudeen shukurah', '18-24', 'shukurattajudeen208@gmail.com', 'Female'),
    ('Abdulsobur Ayofe Olatunde', '25-34', 'olatundeabdulsobur@gmail.com', 'Male'),
    ('Sakina isah', '18-24', 'Sakinaisah393@gmail.com', 'Female'),
    ('Ibrahim Alasan', '18-24', 'alasanibrahim010@gmail.com', 'Male'),
    ('Hussaini idris', '18-24', 'hussainiidris933@gmail.com', 'Male'),
    ('Sadiq Ahmad Tijani', '18-24', 'ahmadtijanisadiq193@gmail.com', 'Male'),
    ('Yusuf Ali hassan', '18-24', 'Yusufaliwaziri@gmail.com', 'Male'),
    ('Gambo Shehu', '25-34', 'Gamboshehu90@Gmail.com', 'Male'),
    ('Amina Aminu Usman', '18-24', 'aaminuusaman8888@gmail.com', 'Female'),
    ('Abdulazeez Zulfat', '25-34', 'zulfahabdulazeez513@gmail.com', 'Female'),
    ('Ahmad Fatima Zahra', '18-24', 'ahmerdfateemerh@gmail.com', 'Female'),
    ('Osobe Chinelo Faith', 'Under 18', 'ocf9335@gmail.com', 'Female'),
    ('Zahraddeen abdulmumin', '25-34', 'zahraddeenabdulmumin3@gmail.com', 'Male'),
    ('Faisal ismail', '18-24', 'Ismailfaisal164@gmail.com', 'Male'),
    ('Abbas Munirat', '18-24', 'muniratize984@gmail.com', 'Female'),
    ('MUSA HAYATUDEEN', '18-24', 'hayatmusa442@gmail.com', 'Male'),
    ('Ibrahim lawal Isah', '25-34', 'ibrahimlawalisah18@gmail.com', 'Male'),
    ('Mohammed Aishat hady', '25-34', 'Aishathady@gmail.com', 'Female'),
    ('Ashafa Bashir', '18-24', 'ashafabashir26@gmail.com', 'Male'),
    ('Haruna abba umar', '18-24', 'Umarharunaabba96@gmail.com', 'Male'),
    ('Mam Teslimat Omolola', '18-24', 'teslimat.omolola@gmail.com', 'Female'),
    ('Saifullahi khalid', '18-24', 'sayyadisk64@gmail.com', 'Male'),
    ('Fatima Nasiru Liman', '25-34', 'fatnabright2000@gmail.com', 'Female'),
    ('Muhammad shakuru suleiman', '18-24', 'Muhammadsssuleiman2000@gmail.com', 'Male'),
    ('Zeenat Abdullahi', '18-24', 'zeenatabdullahi3@gmail.com', 'Female'),
    ('Mardiya muhammed', '18-24', 'Fatimamuhammed9836@gmail.com', 'Female'),
    ('Olawale Oduola Hezekiah', '18-24', 'Olawaletimileyin10@gmail.com', 'Male'),
    ('Lawal Habeeb Taiwo', '25-34', 'lawalhabeebtaiwo@gmail.com', 'Male'),
    ('Muhammad Al Amin Zubair', '18-24', 'Muhdzub2004@gmail.com', 'Male'),
    ('Adeoti Zainab Olamide', '25-34', 'olamidebola18@gmail.com', 'Female'),
    ('Samuel Godwin Eneji', '25-34', 'Samuelgodwineneji@gmail.com', 'Male'),
    ('Ibrahim Rukayy', '18-24', 'Ibrahimrukayya589@gmail.com', 'Female'),
    ('SHUAIBU HARUNA WAKILI', '18-24', 'wakiliharuna9@gmail.com', 'Male'),
    ('Aza Japheth', '18-24', 'japhethaza2@gmail.com', 'Male'),
    ('Rumaitha Adegbindin Adepeju', '18-24', 'adegbindinrumaitha451@gmail.com', 'Female'),
    ('Abdulmalik Maryam Mairo', '18-24', 'abdulmalikmaryam21@gmail.com', 'Female'),
    ('Farihah Ifesayp Hussein', '25-34', 'husseinfarihah13@gmail.com', 'Female'),
    ('Yuusuf Abdullahi kayode', '25-34', 'Yuusab10@gmail.com', 'Male'),
    ('Ogedengbe Jesse', '18-24', 'jesseogedengbe@gmail.com', 'Male'),
    ('YAKUBU UTHMAN ABDULLAHI', '25-34', 'uthmanyakubabdullahi@gmail.com', 'Male'),
    ('Afolabi Hamid Shinaayomi', 'Under 18', 'hamidafolabi22@gmail.com', 'Male')

), cleaned AS (
  SELECT DISTINCT ON (LOWER(TRIM(email)))
         TRIM(name) AS name,
         NULLIF(TRIM(age_band), '') AS age_band,
         LOWER(TRIM(email)) AS email,
         NULLIF(INITCAP(LOWER(TRIM(gender))), '') AS gender
  FROM raw_records
  WHERE NULLIF(TRIM(name), '') IS NOT NULL
    AND NULLIF(TRIM(email), '') IS NOT NULL
    AND LOWER(TRIM(email)) ~ '^[a-z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$'
  ORDER BY LOWER(TRIM(email)), name
)
INSERT INTO users (name, email, password_hash, role, dob, gender, language)
SELECT name,
       email,
       '$2a$10$CwTycUXWue0Thq9StjUM0uJ8RRCfD.tI3/GRiJk1mA5mQnGTN.Kyi',
       'patient',
       CASE age_band
         WHEN 'Under 18' THEN '2010-01-01'
         WHEN '18-24' THEN '2004-01-01'
         WHEN '25-34' THEN '1996-01-01'
         WHEN '35-44' THEN '1986-01-01'
         WHEN '45-54' THEN '1976-01-01'
         WHEN '55-64' THEN '1966-01-01'
         ELSE NULL
       END,
       gender,
       'English'
FROM cleaned c
WHERE NOT EXISTS (
  SELECT 1 FROM users u WHERE LOWER(u.email) = c.email
);
